<div class="page-wrapper orders-hub">
  <header class="page-hero page-hero--compact"><p class="section-eyebrow reveal">Espace commandes</p><h1 class="section-title reveal">Mes <em>commandes</em></h1><p class="section-sub reveal">Suivez vos achats, payez une commande en attente ou retrouvez une commande passée — sans compte obligatoire.</p></header>
  <section class="section section--flush-top">
    <?php if ($recent_orders): ?><div class="orders-hub-section reveal"><div class="orders-hub-section-head"><h2 class="form-panel-title">Commandes récentes</h2><p class="form-panel-hint">Sur cet appareil<?= Auth::check() ? ' · compte connecté' : ' · mode invité' ?></p></div><div class="order-card-grid"><?php foreach ($recent_orders as $o): ?><article class="order-card"><a href="<?= e(url('/suivi-commande/' . $o['id'])) ?>" class="order-card__ref"><?= e($o['public_ref']) ?></a><p class="order-card__meta"><?= e(order_status_label($o['status'])) ?> · <?= e(money_eur((int) $o['total_cents'])) ?></p><p class="order-card__date"><?= e($o['created_at']) ?></p></article><?php endforeach; ?></div></div><?php endif; ?>
    <div class="tracking-layout tracking-layout--hub">
      <div class="form-panel reveal"><h2 class="form-panel-title">Retrouver une commande</h2><p class="form-panel-hint">Référence (<code>YM-…</code>) + e-mail utilisé au checkout.</p><form method="post" class="tracking-form"><?= csrf_field() ?><div class="field-group"><label class="field-label" for="order_ref">N° de commande</label><input id="order_ref" class="field-input" type="text" name="public_ref" required placeholder="YM-20260615-ABC123" value="<?= e($tracking_ref) ?>"></div><div class="field-group"><label class="field-label" for="email">E-mail</label><input id="email" class="field-input" type="email" name="email" required autocomplete="email" placeholder="vous@exemple.com" value="<?= e($tracking_email) ?>"></div><button type="submit" class="btn-primary">Afficher ma commande</button></form></div>
      <aside class="orders-trust-panel reveal"><h2 class="form-panel-title">Acheter en confiance</h2><ul class="orders-trust-list"><li><span aria-hidden="true">📦</span> Suivi en temps réel de votre commande</li><li><span aria-hidden="true">🔒</span> Paiement sécurisé (carte, virement, PayPal)</li><li><span aria-hidden="true">🚚</span> Livraison suivie jusqu’à votre porte</li><li><span aria-hidden="true">💬</span> Support par e-mail sous 24–48 h</li></ul><p class="form-panel-hint">Besoin d’aide ? <a href="mailto:<?= e($shop_contact_email) ?>"><?= e($shop_contact_email) ?></a> · <a href="<?= e(url('/contact')) ?>">Contact</a></p></aside>
    </div>
  </section>
</div>
