# -*- coding: utf-8 -*-
"""Catalogue marketplace Yombal Market — smartphones, électroménager, mode, chaussures, sacs."""

from models.constants import (
    CATEGORY_BAGAGERIE,
    CATEGORY_CHAUSSURES,
    CATEGORY_ELECTROMENAGER,
    CATEGORY_ELECTRONIQUE,
    CATEGORY_MODE,
)


def _item(
    sku,
    slug,
    name,
    summary,
    category,
    icon,
    price_cents,
    weight_info,
    *,
    origin="Sélection Yombal Market — Groupe YOMBAL",
    usage_tips="",
    conservation="Conserver à l'abri de l'humidité et des chocs.",
    description_extra="",
    stock_qty=20,
):
    desc = (
        f"{summary}\n\n"
        f"Référence proposée sur Yombal Market : qualité contrôlée, "
        f"fiche produit détaillée et livraison suivie.\n\n"
        f"{description_extra}"
    ).strip()
    return {
        "sku": sku,
        "slug": slug,
        "name": name,
        "summary": summary,
        "description": desc,
        "price_cents": price_cents,
        "category": category,
        "icon": icon,
        "origin": origin,
        "weight_info": weight_info,
        "ingredients": "",
        "allergens": "",
        "usage_tips": usage_tips,
        "conservation": conservation,
        "stock_qty": stock_qty,
    }


# —— Smartphones (rayon électronique) ——
SMARTPHONES_CATALOGUE = [
    _item(
        "PHONE-IPHONE-13",
        "iphone-13-128go",
        "iPhone 13 — 128 Go",
        "Écran Super Retina, double appareil photo, autonomie confortable.",
        CATEGORY_ELECTRONIQUE,
        "📱",
        49900,
        "128 Go — boîte + câble",
        usage_tips="Activer avec un compte Apple. Mettre à jour iOS au premier démarrage.",
        description_extra="Modèle reconditionné grade A ou neuf selon stock. Garantie constructeur / vendeur.",
    ),
    _item(
        "PHONE-IPHONE-14",
        "iphone-14-128go",
        "iPhone 14 — 128 Go",
        "Performances fluides, photo jour/nuit, 5G.",
        CATEGORY_ELECTRONIQUE,
        "📱",
        62900,
        "128 Go — boîte + câble",
        description_extra="Idéal quotidien et réseaux sociaux. Coloris selon disponibilité.",
    ),
    _item(
        "PHONE-SAMSUNG-A54",
        "samsung-galaxy-a54",
        "Samsung Galaxy A54",
        "Écran AMOLED, triple photo, autonomie longue.",
        CATEGORY_ELECTRONIQUE,
        "📱",
        34900,
        "128 Go — dual SIM selon lot",
        description_extra="Android à jour, charge rapide. Excellent rapport qualité/prix.",
    ),
    _item(
        "PHONE-SAMSUNG-S23",
        "samsung-galaxy-s23",
        "Samsung Galaxy S23",
        "Flagship compact : photo pro, fluidité et 5G.",
        CATEGORY_ELECTRONIQUE,
        "📱",
        54900,
        "128 Go / 256 Go selon stock",
        description_extra="Série Galaxy S — performances premium pour usage intensif.",
    ),
    _item(
        "PHONE-XIAOMI-13T",
        "xiaomi-13t",
        "Xiaomi 13T",
        "Écran 144 Hz, charge ultra-rapide, photo Leica.",
        CATEGORY_ELECTRONIQUE,
        "📱",
        37900,
        "256 Go — boîte complète",
        description_extra="Alternative Android premium à prix maîtrisé.",
    ),
    _item(
        "PHONE-TECNO-CAMON",
        "tecno-camon-20",
        "Tecno Camon 20",
        "Smartphone accessible, grand écran, bonne autonomie.",
        CATEGORY_ELECTRONIQUE,
        "📱",
        17900,
        "128 Go — dual SIM",
        description_extra="Populaire en Afrique et diaspora — usage quotidien et WhatsApp.",
    ),
]

# —— Électroménager ——
ELECTROMENAGER_CATALOGUE = [
    _item(
        "HOME-MIXEUR",
        "mixeur-plongeant-inox",
        "Mixeur plongeant inox",
        "Puissant, pieds amovibles, idéal sauces et soupes.",
        CATEGORY_ELECTROMENAGER,
        "🥣",
        2990,
        "1 mixeur + accessoires",
        usage_tips="Ne pas immerger le moteur. Nettoyer le pied après chaque usage.",
    ),
    _item(
        "HOME-BOUILLOIRE",
        "bouilloire-electrique-17l",
        "Bouilloire électrique 1,7 L",
        "Chauffe rapide, arrêt auto, filtre antitartre.",
        CATEGORY_ELECTROMENAGER,
        "☕",
        2490,
        "1,7 L — 220–240 V",
    ),
    _item(
        "HOME-FER",
        "fer-repasser-vapeur",
        "Fer à repasser vapeur",
        "Semelle anti-adhérente, débit vapeur réglable.",
        CATEGORY_ELECTROMENAGER,
        "👔",
        3290,
        "1 fer + réservoir",
    ),
    _item(
        "HOME-ASPIRATEUR",
        "aspirateur-balai-sans-fil",
        "Aspirateur balai sans fil",
        "Léger, autonomie multi-surfaces, station de charge.",
        CATEGORY_ELECTROMENAGER,
        "🧹",
        8990,
        "1 aspirateur + 2 embouts",
    ),
    _item(
        "HOME-MICRO",
        "micro-ondes-20l",
        "Micro-ondes 20 L",
        "Compact, plateaux rotatif, programmes express.",
        CATEGORY_ELECTROMENAGER,
        "🍲",
        7990,
        "20 L — 700 W",
    ),
    _item(
        "HOME-FRITEUSE",
        "friteuse-air-5l",
        "Friteuse à air 5 L",
        "Cuisson sans huile, panier XXL pour famille.",
        CATEGORY_ELECTROMENAGER,
        "🍟",
        6990,
        "5 L — thermostat digital",
    ),
    _item(
        "HOME-VENTILO",
        "ventilateur-colonne-oscillant",
        "Ventilateur colonne oscillant",
        "3 vitesses, silencieux, télécommande selon modèle.",
        CATEGORY_ELECTROMENAGER,
        "💨",
        4490,
        "1 colonne — hauteur ~1 m",
    ),
    _item(
        "HOME-MACHINE-CAFE",
        "machine-cafe-filtre",
        "Machine à café filtre",
        "Verseuse 1 L, programmation, maintien au chaud.",
        CATEGORY_ELECTROMENAGER,
        "☕",
        3990,
        "1 machine + filtre permanent",
    ),
]

# —— Habillement ——
MODE_CATALOGUE = [
    _item(
        "MODE-TSHIRT-UNI",
        "tshirt-coton-uni",
        "T-shirt coton uni",
        "Coupe regular, coton doux, plusieurs coloris.",
        CATEGORY_MODE,
        "👕",
        1490,
        "Tailles S–XXL",
        conservation="Laver à 30 °C. Ne pas sécher en machine haute température.",
    ),
    _item(
        "MODE-CHEMISE",
        "chemise-oxford-homme",
        "Chemise Oxford homme",
        "Classique bureau / cérémonie, tissu respirant.",
        CATEGORY_MODE,
        "👔",
        2990,
        "Tailles S–XXL",
    ),
    _item(
        "MODE-ROBE",
        "robe-legere-ete",
        "Robe légère d'été",
        "Coupe fluide, motifs assortis, idéale chaleur.",
        CATEGORY_MODE,
        "👗",
        3490,
        "Tailles S–XL",
    ),
    _item(
        "MODE-JEAN",
        "jean-slim-stretch",
        "Jean slim stretch",
        "Denim stretch confortable, coupe moderne.",
        CATEGORY_MODE,
        "👖",
        3990,
        "Tailles 28–42",
    ),
    _item(
        "MODE-HOODIE",
        "hoodie-molleton",
        "Hoodie molleton",
        "Capuche, poche kangourou, intérieur doux.",
        CATEGORY_MODE,
        "🧥",
        3290,
        "Tailles S–XXL",
    ),
    _item(
        "MODE-ENSEMBLE",
        "ensemble-sport-legging",
        "Ensemble sport legging + top",
        "Textile stretch, idéal sport et maison.",
        CATEGORY_MODE,
        "🏃",
        2790,
        "Tailles S–XL — 2 pièces",
    ),
    _item(
        "MODE-PAGNE",
        "boubou-pagne-unisexe",
        "Boubou / ensemble pagne",
        "Tissus wax / pagne colorés, coupe ample.",
        CATEGORY_MODE,
        "🥻",
        4490,
        "Taille unique / sur mesure léger",
        description_extra="Sélection diaspora — motifs et coloris selon arrivage.",
    ),
]

# —— Chaussures ——
CHAUSSURES_CATALOGUE = [
    _item(
        "SHOE-BASKET",
        "baskets-urbain-unisexe",
        "Baskets urbain unisexe",
        "Confort quotidien, semelle souple, look street.",
        CATEGORY_CHAUSSURES,
        "👟",
        3990,
        "Pointures 36–45",
    ),
    _item(
        "SHOE-RUNNING",
        "chaussures-running-legeres",
        "Chaussures running légères",
        "Amorti, mesh respirant, idéal jogging.",
        CATEGORY_CHAUSSURES,
        "🏃",
        4490,
        "Pointures 36–45",
    ),
    _item(
        "SHOE-SANDALE",
        "sandales-cuir-ete",
        "Sandales cuir d'été",
        "Bride réglable, semelle antidérapante.",
        CATEGORY_CHAUSSURES,
        "🩴",
        2490,
        "Pointures 36–44",
    ),
    _item(
        "SHOE-VILLE",
        "chaussures-ville-homme",
        "Chaussures de ville homme",
        "Cuir synthétique soigné, entretien facile.",
        CATEGORY_CHAUSSURES,
        "👞",
        4990,
        "Pointures 39–45",
    ),
    _item(
        "SHOE-BOTTES",
        "bottes-femme-mi-mollet",
        "Bottes femme mi-mollet",
        "Talon confort, zip latéral, automne/hiver.",
        CATEGORY_CHAUSSURES,
        "👢",
        5490,
        "Pointures 36–41",
    ),
    _item(
        "SHOE-ENFANT",
        "baskets-enfant-coloris",
        "Baskets enfant",
        "Légères, scratch ou lacets selon modèle.",
        CATEGORY_CHAUSSURES,
        "🧒",
        2290,
        "Pointures 28–35",
    ),
]

# —— Sacs & bagagerie ——
BAGAGERIE_CATALOGUE = [
    _item(
        "BAG-SACADOS",
        "sac-a-dos-quotidien-25l",
        "Sac à dos quotidien 25 L",
        "Compartiment laptop, multi-poches, bretelles rembourrées.",
        CATEGORY_BAGAGERIE,
        "🎒",
        3490,
        "25 L — nylon résistant",
    ),
    _item(
        "BAG-CABINE",
        "valise-cabine-rigide",
        "Valise cabine rigide",
        "4 roues, serrure TSA, format avion.",
        CATEGORY_BAGAGERIE,
        "🧳",
        7990,
        "Cabine ~55 cm",
    ),
    _item(
        "BAG-BANDOULIERE",
        "sac-bandouliere-urbain",
        "Sac bandoulière urbain",
        "Compact, anti-vol léger, idéal trajet.",
        CATEGORY_BAGAGERIE,
        "👜",
        2490,
        "1 sac — bandoulière réglable",
    ),
    _item(
        "BAG-WEEKEND",
        "sac-weekend-50l",
        "Sac week-end 50 L",
        "Grand volume, poignées + bandoulière.",
        CATEGORY_BAGAGERIE,
        "🛍️",
        3990,
        "50 L",
    ),
    _item(
        "BAG-ECOLE",
        "cartable-ecole-renforce",
        "Cartable école renforcé",
        "Dos ergonomique, compartiments cahiers.",
        CATEGORY_BAGAGERIE,
        "📚",
        2990,
        "Volume scolaire",
    ),
    _item(
        "BAG-POCHETTE",
        "pochette-voyage-documents",
        "Pochette voyage documents",
        "Passeport, cartes, billets — tour de cou.",
        CATEGORY_BAGAGERIE,
        "🛂",
        1290,
        "1 pochette RFID selon lot",
    ),
]

MARKETPLACE_CATALOGUE = (
    SMARTPHONES_CATALOGUE
    + ELECTROMENAGER_CATALOGUE
    + MODE_CATALOGUE
    + CHAUSSURES_CATALOGUE
    + BAGAGERIE_CATALOGUE
)

MARKETPLACE_SLUGS = frozenset(p["slug"] for p in MARKETPLACE_CATALOGUE)
