# -*- coding: utf-8 -*-
"""Catalogue Univers Diaspora / LabelAfrik — prix et fiches produits."""

from models.constants import (
    CATEGORY_BOISSONS,
    CATEGORY_CEREALES,
    CATEGORY_CONDIMENTS,
    CATEGORY_CONSERVES,
    CATEGORY_COSMETIQUE,
    CATEGORY_FRUITS,
    CATEGORY_HUILES,
    CATEGORY_LEGUMINEUSES,
    CATEGORY_MIELS,
    CATEGORY_POISSON,
    CATEGORY_SNACKS,
    CATEGORY_DESSERTS,
    CATEGORY_VIANDES,
)

_BRAND = "LabelAfrik · Univers Diaspora"
_ORIGIN = "Sénégal & Afrique de l'Ouest — LabelAfrik"


def _euros(v):
    return int(round(float(v) * 100))


def _lf(
    sku,
    slug,
    name,
    summary,
    category,
    icon,
    price_euros,
    weight_info,
    *,
    description_extra="",
    ingredients="",
    allergens="",
    usage_tips="",
    conservation="À l'abri de la lumière et de l'humidité.",
):
    desc = (
        f"{summary}\n\n"
        f"Produit {_BRAND} — L'Afrique, dans chaque grain.\n\n"
        f"{description_extra}"
    ).strip()
    return {
        "sku": sku,
        "slug": slug,
        "name": name,
        "summary": summary,
        "description": desc,
        "price_cents": _euros(price_euros),
        "category": category,
        "icon": icon,
        "origin": _ORIGIN,
        "weight_info": weight_info,
        "ingredients": ingredients,
        "allergens": allergens,
        "usage_tips": usage_tips,
        "conservation": conservation,
    }


# Mises à jour des produits déjà en boutique (photos existantes)
LABELAFRIK_UPDATES = {
    "thiakry-400g": _lf(
        "LF-THIAKRY",
        "thiakry-400g",
        "Thiakhry",
        "Dessert africain onctueux à base d'arraw de mil — sans gluten.",
        CATEGORY_DESSERTS,
        "🍮",
        3,
        "400 g",
        description_extra=(
            "Délicieux avec du lait, du yaourt ou des fruits. "
            "Tradition gourmande et nutritive de nos terroirs."
        ),
    ),
    "fonio-500g": _lf(
        "LF-FONIO",
        "fonio-500g",
        "Fonio",
        "Céréale ancestrale sans gluten — graine du passé, saveur d'avenir.",
        CATEGORY_CEREALES,
        "✨",
        4,
        "500 g",
        description_extra="Léger, nutritif, cuisson rapide (~5 min). Meilleur que le quinoa.",
    ),
    "bouye-baobab-250g": _lf(
        "LF-BAOBAB",
        "bouye-baobab-250g",
        "Baobab",
        "Poudre de fruit de baobab — superaliment riche en vitamine C.",
        CATEGORY_BOISSONS,
        "🌳",
        3.9,
        "250 g",
        description_extra="L'arbre de vie africain. Idéal en jus, smoothies, yaourts et pâtisseries.",
    ),
    "farine-niebe-500g": _lf(
        "LF-NIEBE",
        "farine-niebe-500g",
        "Niébé",
        "Légumineuse africaine riche en protéines végétales.",
        CATEGORY_LEGUMINEUSES,
        "🫘",
        4,
        "500 g",
        description_extra="Couscous, beignets akara, soupes et plats mijotés. Sans gluten.",
    ),
    "kinkeliba-80g": _lf(
        "LF-KINKELIBA",
        "kinkeliba-80g",
        "Kinkeliba",
        "Infusion bien-être d'Afrique — digestive et tonifiante.",
        CATEGORY_BOISSONS,
        "🍃",
        2.5,
        "80 g",
        description_extra="Sans caféine. Infusion 5–8 min, chaude ou froide.",
    ),
    "bissap-seche-200g": _lf(
        "LF-BISSAP",
        "bissap-seche-200g",
        "Bissap",
        "Fleurs d'hibiscus — rouge & blanc, infusion bien-être.",
        CATEGORY_BOISSONS,
        "🌺",
        2.5,
        "200 g",
        description_extra="Rouge : vitalité acidulée. Blanc : douceur et fraîcheur.",
    ),
    "gingembre-poudre-100g": _lf(
        "LF-GINGEMBRE",
        "gingembre-poudre-100g",
        "Gingembre",
        "Épice africaine 100 % naturelle — énergie et digestion.",
        CATEGORY_CONDIMENTS,
        "🫚",
        2,
        "100 g",
        description_extra="Plats, infusions, pâtisseries et smoothies.",
    ),
    "miel-thym-500g": _lf(
        "LF-MIEL",
        "miel-thym-500g",
        "Miel",
        "Miel d'acacia du Sénégal — douceur délicate et énergisante.",
        CATEGORY_MIELS,
        "🍯",
        5,
        "500 g",
        description_extra="Récolté au cœur des acacias. Boissons, desserts et bien-être.",
    ),
    "beurre-karite-brut-150g": _lf(
        "LF-KARITE",
        "beurre-karite-brut-150g",
        "Karité pur",
        "Beurre de karité biologique — soin peau et cheveux.",
        CATEGORY_COSMETIQUE,
        "✨",
        3,
        "150 g",
        description_extra="100 % naturel, vitamines A, D, E et F. Biosene / LabelAfrik.",
    ),
    "mil-millet-1kg": _lf(
        "LF-MIL",
        "mil-millet-1kg",
        "Mil (dougoupe)",
        "Céréale de base — bouillies, thiéré et fondé.",
        CATEGORY_CEREALES,
        "🌿",
        2.5,
        "1 kg",
    ),
    "tamarin-pulpe-200g": _lf(
        "LF-DAKHAR",
        "tamarin-pulpe-200g",
        "Dakhar (Tamarin)",
        "Pulpe acidulée pour jus et sauces traditionnelles.",
        CATEGORY_FRUITS,
        "🍫",
        2.9,
        "200 g",
    ),
    "cafe-touba-250g": _lf(
        "LF-CAFE-TOUBA",
        "cafe-touba-250g",
        "Café Touba",
        "Café épicé au diar — spécialité sénégalaise.",
        CATEGORY_BOISSONS,
        "☕",
        3.5,
        "250 g",
    ),
}

# Nouveaux produits phares LabelAfrik (sans photo — emoji vitrine)
LABELAFRIK_PHARES = [
    _lf(
        "LF-ARRAW",
        "arraw-mil-labelafrik",
        "Arraw",
        "Porridge africain sain sans gluten — à base de mil.",
        CATEGORY_CEREALES,
        "🌾",
        3,
        "500 g",
        description_extra="Naturel, nutritif et savoureux pour toute la famille.",
    ),
    _lf(
        "LF-SANKHAL",
        "sankhal-labelafrik",
        "Sankhal",
        "Classique à base de mil — bouillies nourrissantes.",
        CATEGORY_CEREALES,
        "🥣",
        3,
        "500 g",
        description_extra="100 % naturel, sans gluten. Tradition en fête.",
    ),
    _lf(
        "LF-THIERE-LALO",
        "thiere-lalo-labelafrik",
        "Thiéré Lalo",
        "Couscous de mil traditionnel — riche en fibres.",
        CATEGORY_CEREALES,
        "🍲",
        3,
        "500 g",
        description_extra="Plat principal ou version sucrée. Sans gluten.",
    ),
    _lf(
        "LF-SOUNGOUF",
        "soungouf-labelafrik",
        "Soungouf",
        "Farine de mil — base de l'alimentation africaine.",
        CATEGORY_CEREALES,
        "🌾",
        3,
        "500 g",
        description_extra="Bouillies, galettes, pâtes. Énergie quotidienne.",
    ),
    _lf(
        "LF-MORINGA",
        "moringa-poudre-labelafrik",
        "Moringa",
        "Poudre de feuilles — superaliment riche en nutriments.",
        CATEGORY_CONDIMENTS,
        "🌿",
        5,
        "100 g",
        description_extra="Boissons, compléments et cuisine santé.",
    ),
    _lf(
        "LF-GOMBO",
        "gombo-poudre-labelafrik",
        "Gombo",
        "Poudre de gombo 100 % naturelle.",
        CATEGORY_CONDIMENTS,
        "🥬",
        2,
        "100 g",
        description_extra="Épaissit sauces et soupes traditionnelles.",
    ),
    _lf(
        "LF-PATE-ARACHIDE",
        "pate-arachide-labelafrik",
        "Pâte d'arachide",
        "Pâte onctueuse 100 % naturelle — protéines et fibres.",
        CATEGORY_CONDIMENTS,
        "🥜",
        2.5,
        "500 g",
        description_extra="Sauces traditionnelles, tartines et petit-déjeuner.",
    ),
]

LABELAFRIK_RIZ = [
    _lf("UD-RIZ-LP20", "riz-long-parfume-20kg", "Riz long parfumé", "Riz long parfumé — sac 20 kg.", CATEGORY_CEREALES, "🌾", 40, "20 kg"),
    _lf("UD-RIZ-B2-20", "riz-brise-2x-20kg", "Riz brisé 2 fois", "Riz brisé deux fois — sac 20 kg.", CATEGORY_CEREALES, "🌾", 28, "20 kg"),
    _lf("UD-RIZ-B1-20", "riz-brise-1x-20kg", "Riz brisé 1 fois", "Riz brisé une fois — sac 20 kg.", CATEGORY_CEREALES, "🌾", 28.9, "20 kg"),
    _lf("UD-RIZ-LP-45", "riz-long-parfume-45kg", "Riz long parfumé", "Riz long parfumé — sac 4,5 kg.", CATEGORY_CEREALES, "🌾", 12.5, "4,5 kg"),
    _lf("UD-RIZ-B1-5", "riz-brise-1x-5kg", "Riz brisé 1 fois", "Riz brisé une fois — sac 5 kg.", CATEGORY_CEREALES, "🌾", 8.9, "5 kg"),
    _lf("UD-RIZ-B2-5", "riz-brise-2x-5kg", "Riz brisé 2 fois", "Riz brisé deux fois — sac 5 kg.", CATEGORY_CEREALES, "🌾", 7.9, "5 kg"),
    _lf("UD-RIZ-LP-THAI", "riz-long-parfume-thai-1kg", "Riz long parfumé thaï", "Arôme délicat — sac 1 kg.", CATEGORY_CEREALES, "🌾", 2.5, "1 kg"),
    _lf("UD-RIZ-LP-1", "riz-long-parfume-1kg", "Riz long parfumé", "Riz long parfumé — sac 1 kg.", CATEGORY_CEREALES, "🌾", 2.5, "1 kg"),
    _lf("UD-RIZ-B2-1", "riz-brise-2x-1kg", "Riz brisé 2 fois", "Riz brisé deux fois — sac 1 kg.", CATEGORY_CEREALES, "🌾", 1.6, "1 kg"),
    _lf("UD-RIZ-C1-1", "riz-casse-1x-1kg", "Riz cassé 1 fois", "Riz cassé une fois — sac 1 kg.", CATEGORY_CEREALES, "🌾", 1.8, "1 kg"),
]

LABELAFRIK_FARINES = [
    _lf("UD-FR-RIZ", "farine-riz-1kg", "Farine de riz", "Fine et légère — sans gluten.", CATEGORY_CEREALES, "🌾", 1.5, "1 kg"),
    _lf("UD-FR-MIL", "farine-mil-1kg", "Farine de mil", "Riche et nutritive.", CATEGORY_CEREALES, "🌾", 2.9, "1 kg"),
    _lf("UD-FR-MANIOC", "farine-manioc-1kg", "Farine de manioc", "Traditionnelle et polyvalente.", CATEGORY_CEREALES, "🌾", 2.9, "1 kg"),
    _lf("UD-FECULE-PT", "fecule-pomme-de-terre-1kg", "Fécule de pomme de terre", "Épaississant pour sauces et pâtisserie.", CATEGORY_CEREALES, "🥔", 1.2, "1 kg"),
    _lf("UD-FR-MAIS-J", "farine-mais-jaune", "Farine de maïs jaune", "Fine et polyvalente.", CATEGORY_CEREALES, "🌽", 2.2, "1 kg"),
    _lf("UD-FR-MAIS-B", "farine-mais-blanc", "Farine de maïs blanc", "Bouillies et galettes.", CATEGORY_CEREALES, "🌽", 2.25, "1 kg"),
    _lf("UD-GRAIN-MIL", "grain-de-mil", "Grain de mil", "Grains entiers pour bouillies.", CATEGORY_CEREALES, "🌿", 2.5, "1 kg"),
]

LABELAFRIK_HUILES = [
    _lf("UD-HL-TOUR-1", "huile-tournesol-1l", "Huile de tournesol", "Légère — cuisson et assaisonnement.", CATEGORY_HUILES, "🫒", 3.9, "1 L"),
    _lf("UD-HL-ARACH-1", "huile-arachide-1l", "Huile d'arachide", "Riche et savoureuse.", CATEGORY_HUILES, "🥜", 2.9, "1 L"),
    _lf("UD-HL-TOUR-5", "huile-tournesol-5l", "Huile de tournesol", "Format familial 5 L.", CATEGORY_HUILES, "🫒", 17.9, "5 L"),
    _lf("UD-HL-PALME-1", "huile-palme-1l", "Huile de palme", "Parfumée — plats traditionnels.", CATEGORY_HUILES, "🫒", 5, "1 L"),
]

LABELAFRIK_BOISSONS = [
    _lf("UD-SIR-BISSAP", "sirop-bissap-ud", "Sirop de bissap", "Sucré et fruité — boissons rafraîchissantes.", CATEGORY_BOISSONS, "🌺", 5, "50 cl"),
    _lf("UD-SIR-GING", "sirop-gingembre-ud", "Sirop de gingembre", "Épicé et tonifiant.", CATEGORY_BOISSONS, "🫚", 5, "50 cl"),
    _lf("UD-BOIS-GING", "boisson-gingembre-ud", "Boisson de gingembre", "Rafraîchissante et énergisante.", CATEGORY_BOISSONS, "🫚", 5, "1 L"),
    _lf("UD-BISSAP-VRAC", "bissap-rouge-vrac-1kg", "Bissap rouge vrac", "Fleurs d'hibiscus — sac 1 kg.", CATEGORY_BOISSONS, "🌺", 10, "1 kg"),
    _lf("UD-POUD-ARACH", "poudre-arachide-ud", "Poudre d'arachide", "Fine et savoureuse.", CATEGORY_CONDIMENTS, "🥜", 2.9, "500 g"),
    _lf("UD-BOUYE-ZENA", "poudre-baobab-zena-200g", "Poudre de baobab Zena", "Vitamines et fibres — 200 g.", CATEGORY_BOISSONS, "🌳", 3, "200 g"),
    _lf("UD-MIEL-1KG", "miel-fleurs-1kg", "Miel", "Miel de fleurs — pot 1 kg.", CATEGORY_MIELS, "🍯", 9, "1 kg"),
    _lf("UD-LAIT-COCO", "lait-coco-ud", "Lait de coco", "Crémeux — sauces et desserts.", CATEGORY_BOISSONS, "🥥", 2.5, "400 ml"),
]

LABELAFRIK_SNACKS = [
    _lf("UD-CHIPS-PLT-D", "chips-plantain-doux", "Chips de plantain doux", "Croustillantes et légèrement sucrées.", CATEGORY_SNACKS, "🍌", 1, "sachet"),
    _lf("UD-CHIPS-PLT-E", "chips-plantain-epice", "Chips de plantain épicé", "Sucré et relevé.", CATEGORY_SNACKS, "🍌", 1, "sachet"),
    _lf("UD-CHIPS-PLT-S", "chips-plantain-sale", "Chips de plantain salé", "Croustillantes et savoureuses.", CATEGORY_SNACKS, "🍌", 1, "sachet"),
    _lf("UD-BISC-GEM", "biscuits-gem", "Biscuits sucrés Gem", "Croustillants — goûter.", CATEGORY_SNACKS, "🍪", 1.5, "sachet"),
    _lf("UD-SAM-LEG", "samoussas-legumes-halal", "Samoussas légumes halal", "Lot de 20 pièces.", CATEGORY_SNACKS, "🥟", 7.9, "20 pièces"),
    _lf("UD-SAM-POU", "samoussas-poulet-20", "Samoussas poulet", "Lot de 20 pièces.", CATEGORY_SNACKS, "🥟", 5.5, "20 pièces"),
    _lf("UD-ACCRAS", "accras-morue", "Accras de morue", "Beignets savoureux.", CATEGORY_SNACKS, "🐟", 7.9, "sachet"),
]

LABELAFRIK_LEGUMES = [
    _lf("UD-CORNILLES", "cornilles-haricots-blancs", "Cornilles", "Haricots blancs — soupes et ragoûts.", CATEGORY_LEGUMINEUSES, "🫘", 2.5, "500 g"),
    _lf("UD-HAR-NOIR", "haricots-noirs-tersol", "Haricots noirs", "Tersol — protéines et fibres.", CATEGORY_LEGUMINEUSES, "🫘", 1.99, "500 g"),
    _lf("UD-ARACH-CRU", "arachides-crues-blanches-1kg", "Arachides crues", "Blanches — 1 kg.", CATEGORY_LEGUMINEUSES, "🥜", 4.75, "1 kg"),
]

LABELAFRIK_CONDIMENTS = [
    _lf("UD-DAKATINE", "pate-arachide-dakatine", "Pâte d'arachide Dakatine", "Onctueuse — sauces et tartines.", CATEGORY_CONDIMENTS, "🥜", 5.9, "pot"),
    _lf("UD-PIM-ANT", "piment-rouge-antillais", "Piment rouge antillais", "Très piquant — arôme antillais.", CATEGORY_CONDIMENTS, "🌶️", 5.9, "pot"),
    _lf("UD-ADJIA", "bouillon-adjia", "Bouillon Adjia", "Épices en poudre — saveur rapide.", CATEGORY_CONDIMENTS, "🧂", 5.9, "sachet"),
    _lf("UD-JUMBO-RAM", "jumbo-ramadan", "Jumbo Ramadan", "Bouillon spécial Ramadan.", CATEGORY_CONDIMENTS, "🧂", 5.9, "sachet"),
    _lf("UD-PATE-25", "pate-arachide-25kg", "Pâte d'arachide", "Pot 2,5 kg.", CATEGORY_CONDIMENTS, "🥜", 15, "2,5 kg"),
    _lf("UD-PATE-BON", "pate-arachide-bonmafe", "Pâte d'arachide Bonmafe", "Pot 850 g.", CATEGORY_CONDIMENTS, "🥜", 7.9, "850 g"),
    _lf("UD-PATE-PCD", "pate-arachide-pcd-500g", "Pâte d'arachide PCD", "Pot 500 g.", CATEGORY_CONDIMENTS, "🥜", 2.5, "500 g"),
]

LABELAFRIK_FRUITS = [
    _lf("UD-DATTES-SEC", "dattes-seches-ud", "Dattes sèches", "Sucrées et nutritives.", CATEGORY_FRUITS, "🌴", 3.9, "500 g"),
    _lf("UD-DATTES-BR", "dattes-branchees-ud", "Dattes branchées", "Fraîches et savoureuses.", CATEGORY_FRUITS, "🌴", 5.9, "500 g"),
    _lf("UD-DATTES-DEM", "dattes-demi-seches-ud", "Dattes demi-sèches", "Moelleuses et naturellement sucrées.", CATEGORY_FRUITS, "🌴", 3.9, "500 g"),
    _lf("UD-RAISIN-SEC", "raisins-secs-golden", "Raisins secs golden", "Moelleux — collations.", CATEGORY_FRUITS, "🍇", 3.9, "500 g"),
    _lf("UD-TAM-150", "dakhar-sachet-150g", "Dakhar (Tamarin)", "Sachet 150 g.", CATEGORY_FRUITS, "🍫", 2, "150 g"),
    _lf("UD-TAM-375", "dakhar-sachet-375g", "Dakhar (Tamarin)", "Sachet 375 g.", CATEGORY_FRUITS, "🍫", 3.9, "375 g"),
]

LABELAFRIK_ALIMENTS = [
    _lf("UD-FOUFOU", "foufou-farine-manioc", "Foufou", "Farine de manioc prête à cuire.", CATEGORY_CEREALES, "🌾", 2.9, "500 g"),
    _lf("UD-FUFU", "fufu-farine-plantain", "Fufu plantain", "Farine de plantain — texture moelleuse.", CATEGORY_CEREALES, "🍌", 4.95, "600 g"),
    _lf("UD-FIONO", "fiono-guinee", "Fiono Guinée", "Préparation traditionnelle manioc/céréales.", CATEGORY_CEREALES, "🌾", 3.9, "500 g"),
    _lf("UD-THIACRY", "thiacry-de-mil", "Thiacry de mil", "Dessert traditionnel au mil et lait.", CATEGORY_DESSERTS, "🍮", 1.8, "400 g"),
    _lf("UD-CORNED", "corned-beef-halal", "Corned beef halal", "Prêt à consommer — repas rapides.", CATEGORY_VIANDES, "🥫", 2.5, "340 g"),
    _lf("UD-CITRON", "jus-citron-sicile-1l", "Jus de citron", "Citron jaune de Sicile — 1 L.", CATEGORY_BOISSONS, "🍋", 3.9, "1 L"),
    _lf("UD-GHEE", "butter-ghee", "Beurre ghee", "Beurre clarifié — cuisson et friture.", CATEGORY_HUILES, "🧈", 7.9, "500 g"),
    _lf("UD-MADD-230", "maad-230g", "Maad", "Boîte 230 g — fruit acidulé.", CATEGORY_FRUITS, "🍋", 4.9, "230 g"),
    _lf("UD-MADD-400", "maad-400g", "Maad", "Boîte 400 g — fruit acidulé.", CATEGORY_FRUITS, "🍋", 7.9, "400 g"),
    _lf("UD-BISSAP-Z", "bissap-rouge-zena", "Bissap blanc Zena", "Infusion douce et rafraîchissante.", CATEGORY_BOISSONS, "🌺", 2.5, "125 g"),
    _lf("UD-POISS-F", "poisson-fume-ud", "Poisson fumé", "Séché et fumé — soupes, sauces, thiéb.", CATEGORY_POISSON, "🐟", 18, "500 g"),
    _lf("UD-BARBET", "rouge-barbet-ud", "Rouge barbet", "Poisson frais — friture ou grillade.", CATEGORY_POISSON, "🐟", 7.5, "1 kg"),
]

LABELAFRIK_CONSERVES = [
    _lf("UD-TROFAI-35", "sauce-trofai-palmier-350", "Sauce Trofai", "Graine de palmier — pot 350 g.", CATEGORY_CONDIMENTS, "🫙", 3.5, "350 g"),
    _lf("UD-TROFAI-41", "sauce-trofai-palmier-410", "Sauce Trofai", "Graine de palmier — pot 410 g.", CATEGORY_CONDIMENTS, "🫙", 4.1, "410 g"),
    _lf("UD-TOM-ROLLI", "concentre-tomates-rolli", "Concentré de tomates Rolli", "Tube 880 g.", CATEGORY_CONSERVES, "🍅", 4.25, "880 g"),
    _lf("UD-TOM-2KG", "concentre-tomates-2kg", "Concentré de tomates", "Pot 2 kg.", CATEGORY_CONSERVES, "🍅", 7.5, "2 kg"),
    _lf("UD-SARD-P", "pate-sardinelle-pinton", "Pâte de sardinelle Pinton", "Sauces et plats de riz.", CATEGORY_POISSON, "🐟", 2.9, "pot"),
    _lf("UD-SARD-T", "sardinelle-pilchards-tomate", "Sardinelles à la sauce tomate", "Prêtes à consommer.", CATEGORY_POISSON, "🐟", 2.5, "boîte"),
    _lf("UD-NIDO-400", "poudre-lait-nido-400g", "Lait en poudre Nido", "Poudre Nido en sachet — riche en calcium et nutriments.", CATEGORY_BOISSONS, "🥛", 8.9, "400 g"),
    _lf("UD-NIDO-900", "poudre-lait-nido-900g", "Lait en poudre Nido", "Poudre Nido en sachet — riche en calcium et nutriments.", CATEGORY_BOISSONS, "🥛", 15.9, "900 g"),
    _lf("UD-NIDO-18", "poudre-lait-nido-1800g", "Lait en poudre Nido", "Poudre Nido en sachet — riche en calcium et nutriments.", CATEGORY_BOISSONS, "🥛", 26.9, "1,8 kg"),
    _lf("UD-NIDO-25", "poudre-lait-nido-2500g", "Lait en poudre Nido", "Poudre Nido en sachet — riche en calcium et nutriments.", CATEGORY_BOISSONS, "🥛", 34.9, "2,5 kg"),
    _lf("UD-STAR", "the-instantane-starling", "Thé instantané Starling", "Préparation rapide aromatique.", CATEGORY_BOISSONS, "☕", 2.5, "sachet"),
    _lf("UD-FOSTER", "boisson-instantanee-foster", "Boisson instantanée Foster Clark's", "Rafraîchissante et facile.", CATEGORY_BOISSONS, "🥤", 5, "sachet"),
]

LABELAFRIK_SNACKS_EXTRA = [
    _lf("UD-SAM-MOUT", "samoussas-mouton-halal", "Samoussas mouton halal", "Lot de 20 pièces.", CATEGORY_SNACKS, "🥟", 7.9, "20 pièces"),
    _lf("UD-NEMS-P", "nems-poulet-halal-50", "Nems poulet halal", "Lot de 50 pièces.", CATEGORY_SNACKS, "🥟", 22.5, "50 pièces"),
    _lf("UD-NEMS-CP", "nems-crevettes-poulet-halal", "Nems crevettes & poulet", "Lot de 50 pièces halal.", CATEGORY_SNACKS, "🥟", 25.9, "50 pièces"),
    _lf("UD-FAT-POISS", "fataya-poisson-10", "Fataya au poisson", "Lot de 10 pièces.", CATEGORY_SNACKS, "🥟", 6.9, "10 pièces"),
    _lf("UD-FAT-VIAN", "fataya-viande-10", "Fataya à la viande", "Lot de 10 pièces.", CATEGORY_SNACKS, "🥟", 7.5, "10 pièces"),
    _lf("UD-RIZ-C2", "riz-casse-2x-1kg", "Riz cassé 2 fois", "Sac 1 kg — absorption des sauces.", CATEGORY_CEREALES, "🌾", 1.6, "1 kg"),
    _lf(
        "UD-SOMBI",
        "sombi-riz-au-lait",
        "Riz au lait (sombi)",
        "Dessert sénégalais crémeux — riz cuit dans le lait sucré.",
        CATEGORY_DESSERTS,
        "🍚",
        3.5,
        "400 g",
        description_extra=(
            "Le sombi (riz au lait) est un classique du goûter et des fêtes : "
            "onctueux, parfumé à la vanille ou à la cannelle selon la préparation."
        ),
        ingredients="Riz, lait, sucre, arômes (selon lot).",
        allergens="Lait.",
        usage_tips="Servir frais. Réchauffer doucement si besoin.",
        conservation="Au frais après ouverture. Consommer rapidement.",
    ),
    _lf(
        "UD-THIAK-LAIT",
        "thiakhri-au-lait",
        "Thiakhri au lait",
        "Arraw de mil au lait — dessert onctueux et nourrissant.",
        CATEGORY_DESSERTS,
        "🍮",
        3.5,
        "400 g",
        description_extra=(
            "Thiakhri (dégué) préparé au lait : texture légère, goût doux du mil. "
            "Idéal au petit-déjeuner ou en dessert."
        ),
        ingredients="Arraw de mil, lait, sucre (selon lot).",
        allergens="Lait. Peut contenir des traces de gluten selon préparation.",
        usage_tips="Servir bien frais. Ajouter raisins ou fruits secs selon goût.",
        conservation="Au frais après ouverture.",
    ),
    _lf(
        "UD-NGALAKH",
        "thiakhri-ngalakh",
        "Thiakhri pâte d'arachide (ngalakh)",
        "Dessert de mil à la pâte d'arachide — ngalakh traditionnel.",
        CATEGORY_DESSERTS,
        "🥜",
        4.5,
        "400 g",
        description_extra=(
            "Le ngalakh marie thiakhri (arraw de mil), pâte d'arachide et souvent baobab : "
            "riche, sucré-salé subtil, incontournable des tables sénégalaises."
        ),
        ingredients="Arraw de mil, pâte d'arachide, sucre, baobab (selon lot).",
        allergens="Arachides. Lait possible selon préparation.",
        usage_tips="Servir frais. Remuer avant dégustation si la pâte se dépose.",
        conservation="Au frais après ouverture.",
    ),
]

LABELAFRIK_MER = [
    _lf(
        "UD-MER-T5",
        "merou-thiof-entier-5kg",
        "Mérou Thiof entier",
        "Frais et savoureux — carton de 5 kg.",
        CATEGORY_POISSON,
        "🐟",
        50,
        "carton 5 kg",
        description_extra="Idéal pour griller, cuire ou préparer des plats de poisson traditionnels.",
    ),
    _lf(
        "UD-MER-T5ST",
        "merou-thiof-sans-tete-5kg",
        "Mérou Thiof sans tête",
        "Gros mérou sans tête — carton de 5 kg.",
        CATEGORY_POISSON,
        "🐟",
        65,
        "carton 5 kg",
    ),
    _lf(
        "UD-MER-T10",
        "merou-thiof-entier-10kg",
        "Mérou Thiof entier",
        "Frais et savoureux — carton de 10 kg.",
        CATEGORY_POISSON,
        "🐟",
        90,
        "carton 10 kg",
    ),
    _lf(
        "UD-MER-T10ST",
        "merou-thiof-sans-tete-10kg",
        "Mérou Thiof sans tête",
        "Gros mérou sans tête — carton de 10 kg.",
        CATEGORY_POISSON,
        "🐟",
        125,
        "carton 10 kg",
    ),
    _lf(
        "UD-MER-PT",
        "petits-merous-thiof",
        "Petits mérous Thiof",
        "Frais et savoureux — parfaits pour griller ou frire.",
        CATEGORY_POISSON,
        "🐟",
        10,
        "au kg",
    ),
    _lf(
        "UD-MER-DD10",
        "dorade-diaregne-tete-10kg",
        "Dorade Diaregne avec tête",
        "Grosses dorades fraîches — carton de 10 kg.",
        CATEGORY_POISSON,
        "🐟",
        75,
        "carton 10 kg",
    ),
    _lf(
        "UD-MER-DD5",
        "dorade-diaregne-tete-5kg",
        "Dorade Diaregne avec tête",
        "Grosses dorades fraîches — carton de 5 kg.",
        CATEGORY_POISSON,
        "🐟",
        40,
        "carton 5 kg",
    ),
    _lf(
        "UD-MER-DD5ST",
        "dorade-diaregne-sans-tete-5kg",
        "Dorade Diaregne sans tête",
        "Grosses dorades sans tête — carton de 5 kg.",
        CATEGORY_POISSON,
        "🐟",
        80,
        "carton 5 kg",
    ),
    _lf(
        "UD-MER-DV10",
        "dorade-vivaneau-10kg",
        "Dorade plate Vivaneau",
        "Grosses dorades plates — carton de 10 kg.",
        CATEGORY_POISSON,
        "🐟",
        100,
        "carton 10 kg",
    ),
    _lf(
        "UD-MER-D58",
        "dorade-500-800-5kg",
        "Dorade 500–800 g",
        "Vidée, écaillée — carton de 5 kg.",
        CATEGORY_POISSON,
        "🐟",
        40,
        "carton 5 kg",
    ),
    _lf(
        "UD-MER-D46",
        "dorade-400-600-5kg",
        "Dorade 400–600 g",
        "Vidée, écaillée — carton de 5 kg.",
        CATEGORY_POISSON,
        "🐟",
        35,
        "carton 5 kg",
    ),
    _lf(
        "UD-MER-D10",
        "dorade-1000-plus-5kg",
        "Dorade 1000 g+",
        "Vidée, écaillée — carton de 5 kg.",
        CATEGORY_POISSON,
        "🐟",
        45,
        "carton 5 kg",
    ),
    _lf(
        "UD-MER-CB46",
        "capitaine-bar-400-600-5kg",
        "Capitaine Bar (Ombrine)",
        "400 à 600 g — carton de 5 kg.",
        CATEGORY_POISSON,
        "🐟",
        45,
        "carton 5 kg",
    ),
    _lf(
        "UD-MER-BAR5",
        "barracuda-seud-5kg",
        "Barracuda Seud",
        "Frais et savoureux — carton de 5 kg.",
        CATEGORY_POISSON,
        "🐟",
        40,
        "carton 5 kg",
    ),
    _lf(
        "UD-MER-CB68",
        "capitaine-bar-600-800-10kg",
        "Capitaine Bar (Ombrine)",
        "600 à 800 g — carton de 10 kg.",
        CATEGORY_POISSON,
        "🐟",
        90,
        "carton 10 kg",
    ),
    _lf(
        "UD-MER-BAR10",
        "barracuda-seud-10kg",
        "Barracuda Seud",
        "Conditionné en carton de 10 kg.",
        CATEGORY_POISSON,
        "🐟",
        70,
        "carton 10 kg",
        description_extra="Idéal pour grillades, fumé ou en sauce.",
    ),
    _lf(
        "UD-MER-SOLE",
        "sole-karabot",
        "Grosse sole Karabot",
        "Poisson plat à chair fine et délicate.",
        CATEGORY_POISSON,
        "🐟",
        22,
        "pièce",
    ),
    _lf(
        "UD-MER-SARD",
        "sardinelle-yaboye",
        "Sardinelle Yaboye",
        "Poisson savoureux pour plats traditionnels sénégalais.",
        CATEGORY_POISSON,
        "🐟",
        10,
        "sachet",
    ),
    _lf(
        "UD-MER-TILM",
        "tilapia-moyen-senegal",
        "Tilapia moyen Sénégal",
        "Chair tendre — four, poêle ou grill.",
        CATEGORY_POISSON,
        "🐟",
        20,
        "carton",
    ),
    _lf(
        "UD-MER-CHIN",
        "chinchard-600-900-10kg",
        "Chinchard entier 600/900",
        "Carton de 10 kg — chair ferme et goûteuse.",
        CATEGORY_POISSON,
        "🐟",
        35,
        "carton 10 kg",
    ),
    _lf(
        "UD-MER-TILX",
        "tilapia-gros-xxl-10kg",
        "Tilapia gros XXL",
        "Carton de 10 kg — grandes préparations.",
        CATEGORY_POISSON,
        "🐟",
        50,
        "carton 10 kg",
    ),
    _lf(
        "UD-MER-MACH",
        "gros-machoiron",
        "Gros machoiron",
        "Chair ferme — plats en sauce ou grillades.",
        CATEGORY_POISSON,
        "🐟",
        8,
        "pièce",
    ),
    _lf(
        "UD-CREV",
        "crevettes-crues-decortiquees",
        "Crevettes crues décortiquées",
        "Fraîches et prêtes à cuisiner.",
        CATEGORY_POISSON,
        "🦐",
        7,
        "sachet",
        description_extra="Sauces, plats sautés et recettes de fruits de mer.",
    ),
    _lf(
        "UD-GAMB",
        "gambas-geantes-sauvages",
        "Gambas géantes sauvages",
        "Fraîches et savoureuses.",
        CATEGORY_POISSON,
        "🦐",
        20,
        "sachet",
        description_extra="Grillées, sautées ou en plats de fruits de mer.",
    ),
    _lf(
        "UD-LANG",
        "queues-langoustes-blanches",
        "Queues de langoustes blanches",
        "Sauvages et fraîches.",
        CATEGORY_POISSON,
        "🦞",
        20,
        "sachet",
        description_extra="Plats raffinés et préparations de fruits de mer.",
    ),
    _lf(
        "UD-CRAB",
        "crabe-mangrove",
        "Crabe de mangrove",
        "Frais et savoureux.",
        CATEGORY_POISSON,
        "🦀",
        14.9,
        "pièce",
    ),
]

LABELAFRIK_VIANDES = [
    _lf(
        "UD-AILES",
        "ailes-poulet-texmex-halal",
        "Ailes de poulet Tex-Mex halal",
        "Lot de 2,5 kg — savoureuses et épicées.",
        CATEGORY_VIANDES,
        "🍗",
        17.5,
        "2,5 kg",
        description_extra="Parfaites pour griller ou cuire au four.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-CUISSES-5",
        "cuisses-poulet-halal-5kg",
        "Cuisses de poulet halal",
        "Sachet 5 kg — volaille halal surgelée.",
        CATEGORY_VIANDES,
        "🍗",
        14.9,
        "5 kg",
        description_extra="Idéales pour yassa, mafé, dg ou rôtissage. Certifiées halal.",
        ingredients="Viande de poulet (halal).",
        usage_tips="Cuire à cœur sans décongélation préalable ou après décongélation au réfrigérateur.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-CUISSES-10",
        "cuisses-poulet-halal-10kg",
        "Cuisses de poulet halal",
        "Carton familial 10 kg — volaille halal surgelée.",
        CATEGORY_VIANDES,
        "🍗",
        24.9,
        "10 kg",
        description_extra="Grand format pour familles et événements. Certifiées halal.",
        ingredients="Viande de poulet (halal).",
        usage_tips="Cuire à cœur. Portionner après décongélation légère si besoin.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-PILONS-5",
        "pilons-poulet-halal-5kg",
        "Pilons de poulet halal",
        "Sachet 5 kg — parfaits pour barbecue et braises.",
        CATEGORY_VIANDES,
        "🍗",
        15.9,
        "5 kg",
        description_extra="Pilon juteux pour poulet braisé, yassa, mafé ou grillades. Halal.",
        ingredients="Viande de poulet (halal).",
        usage_tips="Mariner avant cuisson pour plus de goût.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-AILES-5",
        "ailes-poulet-halal-5kg",
        "Ailes de poulet halal",
        "Sachet 5 kg — ailes nature 3 phalanges.",
        CATEGORY_VIANDES,
        "🍗",
        14.9,
        "5 kg",
        description_extra="Ailes nature pour marinade maison, Tex-Mex ou sauce piquante. Halal.",
        ingredients="Viande de poulet (halal).",
        usage_tips="Four, barbecue ou friteuse — cuire à cœur.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-AILES-TX1",
        "ailes-poulet-texmex-1kg",
        "Ailes de poulet Tex-Mex halal",
        "Format 1 kg — déjà assaisonnées.",
        CATEGORY_VIANDES,
        "🍗",
        8.9,
        "1 kg",
        description_extra="Même recette épicée en petit format. Prêtes à cuire.",
        ingredients="Viande de poulet (halal), épices.",
        usage_tips="Four 200 °C ou barbecue jusqu'à cuisson complète.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-POULE-F",
        "poule-fumee-1kg",
        "Morceaux de poule fumée",
        "1 kg — goût fumé pour sauces et soupes.",
        CATEGORY_VIANDES,
        "🍗",
        6.9,
        "1 kg",
        description_extra="Classique de la cuisine africaine : soupes, sauces, riz gras.",
        ingredients="Viande de poule fumée.",
        usage_tips="Ajouter en début de cuisson pour parfumer le bouillon.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-POULE-E",
        "poule-entiere-halal",
        "Poule entière halal",
        "Environ 1,1 kg — poule Pluvera halal.",
        CATEGORY_VIANDES,
        "🐔",
        4.9,
        "≈ 1,1 kg",
        description_extra="Poule entière pour bouillon, couscous ou plats mijotés. Halal.",
        ingredients="Viande de poule (halal).",
        usage_tips="Décongeler au frais puis mijoter ou rôtir.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-DINDE-A",
        "ailerons-dinde-halal-1kg",
        "Ailerons de dinde halal",
        "1 kg — nature, à mariner.",
        CATEGORY_VIANDES,
        "🦃",
        6.9,
        "1 kg",
        description_extra="Ailerons de dinde pour grillades et sauces. Halal.",
        ingredients="Viande de dinde (halal).",
        usage_tips="Mariner puis griller ou cuire au four.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-BOEUF-Q",
        "queue-boeuf-1kg",
        "Queue de bœuf halal",
        "1 kg — idéale pour sauces et soupes.",
        CATEGORY_VIANDES,
        "🥩",
        16.9,
        "1 kg",
        description_extra="Morceaux de queue de bœuf halal pour sauces onctueuses et plats mijotés.",
        ingredients="Viande de bœuf (halal).",
        usage_tips="Mijoter longuement à feu doux jusqu'à tendreté.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-BOEUF-M",
        "morceaux-boeuf-1kg",
        "Morceaux de bœuf halal",
        "1 kg — pour sauces et grillades.",
        CATEGORY_VIANDES,
        "🥩",
        14.9,
        "1 kg",
        description_extra="Morceaux de bœuf halal pour mafé, yassa viande ou sauces tomate.",
        ingredients="Viande de bœuf (halal).",
        usage_tips="Saisir puis mijoter selon la recette.",
        conservation="Surgelé — conserver à -18 °C.",
    ),

    # —— Agneau & mouton ——
    _lf(
        "UD-AGN-M",
        "morceaux-agneau-halal-1kg",
        "Morceaux d'agneau halal",
        "1 kg — pour sauces et tajines.",
        CATEGORY_VIANDES,
        "🐑",
        18.9,
        "1 kg",
        description_extra="Morceaux d'agneau halal pour mafé, yassa, couscous et plats mijotés.",
        ingredients="Viande d'agneau (halal).",
        usage_tips="Mijoter à feu doux jusqu'à tendreté.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-AGN-C",
        "cotelettes-agneau-halal-1kg",
        "Côtelettes d'agneau halal",
        "1 kg — idéales à griller.",
        CATEGORY_VIANDES,
        "🐑",
        22.9,
        "1 kg",
        description_extra="Côtelettes d'agneau halal pour barbecue, plancha ou four.",
        ingredients="Viande d'agneau (halal).",
        usage_tips="Mariner puis griller à feu vif.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-AGN-G",
        "gigot-agneau-halal",
        "Gigot d'agneau halal",
        "Environ 1,5 kg — pour fêtes et dimanches.",
        CATEGORY_VIANDES,
        "🐑",
        29.9,
        "≈ 1,5 kg",
        description_extra="Gigot d'agneau halal à rôtir ou mijoter. Pièce de choix.",
        ingredients="Viande d'agneau (halal).",
        usage_tips="Décongeler au frais, assaisonner et cuire au four.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-MOUT-M",
        "morceaux-mouton-halal-1kg",
        "Morceaux de mouton halal",
        "1 kg — goût typique des sauces africaines.",
        CATEGORY_VIANDES,
        "🐑",
        16.9,
        "1 kg",
        description_extra="Mouton halal pour sauces, mafé et couscous.",
        ingredients="Viande de mouton (halal).",
        usage_tips="Saisir puis mijoter longuement.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    # —— Bœuf (compléments) ——
    _lf(
        "UD-BOEUF-H",
        "steak-hache-boeuf-halal-1kg",
        "Steak haché bœuf halal",
        "1 kg — pour burgers, kefta et sauces.",
        CATEGORY_VIANDES,
        "🥩",
        12.9,
        "1 kg",
        description_extra="Viande hachée de bœuf halal, pratique au quotidien.",
        ingredients="Viande de bœuf hachée (halal).",
        usage_tips="Cuire à cœur. Former des steaks ou intégrer aux sauces.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-BOEUF-F",
        "foie-boeuf-halal-1kg",
        "Foie de bœuf halal",
        "1 kg — foie frais surgelé.",
        CATEGORY_VIANDES,
        "🥩",
        9.9,
        "1 kg",
        description_extra="Foie de bœuf halal pour poêlées, sauces et recettes traditionnelles.",
        ingredients="Foie de bœuf (halal).",
        usage_tips="Décongeler au frais puis cuire rapidement à la poêle.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-BOEUF-T",
        "tripes-boeuf-halal-1kg",
        "Tripes de bœuf halal",
        "1 kg — pour sauces et plats mijotés.",
        CATEGORY_VIANDES,
        "🥩",
        8.9,
        "1 kg",
        description_extra="Tripes de bœuf halal, classiques des sauces africaines.",
        ingredients="Tripes de bœuf (halal).",
        usage_tips="Bien rincer si besoin, puis mijoter longuement.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-BOEUF-C",
        "cotes-boeuf-halal-1kg",
        "Côtes de bœuf halal",
        "1 kg — à griller ou braiser.",
        CATEGORY_VIANDES,
        "🥩",
        17.9,
        "1 kg",
        description_extra="Côtes de bœuf halal pour barbecue ou sauces.",
        ingredients="Viande de bœuf (halal).",
        usage_tips="Griller à feu vif ou mijoter selon la coupe.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-BOEUF-P",
        "pieds-boeuf-halal-1kg",
        "Pieds de bœuf halal",
        "1 kg — pour sauces gélatineuses.",
        CATEGORY_VIANDES,
        "🥩",
        7.9,
        "1 kg",
        description_extra="Pieds de bœuf halal pour sauces onctueuses et plats traditionnels.",
        ingredients="Pieds de bœuf (halal).",
        usage_tips="Mijoter longtemps jusqu'à tendreté.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    # —— Volaille (compléments) ——
    _lf(
        "UD-FILET-P",
        "filets-poulet-halal-1kg",
        "Filets de poulet halal",
        "1 kg — blancs prêts à cuisiner.",
        CATEGORY_VIANDES,
        "🍗",
        11.9,
        "1 kg",
        description_extra="Filets de poulet halal pour grillades, sauces et plats express.",
        ingredients="Viande de poulet (halal).",
        usage_tips="Poêle, four ou sauce — cuire à cœur.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-HCUISSE",
        "hauts-cuisse-poulet-halal-5kg",
        "Hauts de cuisse poulet halal",
        "Sachet 5 kg — juteux et savoureux.",
        CATEGORY_VIANDES,
        "🍗",
        15.9,
        "5 kg",
        description_extra="Hauts de cuisse halal pour rôtissage, sauces et grillades.",
        ingredients="Viande de poulet (halal).",
        usage_tips="Mariner puis cuire au four ou mijoter.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-PINTADE",
        "pintade-entiere-halal",
        "Pintade entière halal",
        "Environ 1,5 kg — volaille fine.",
        CATEGORY_VIANDES,
        "🐔",
        9.9,
        "≈ 1,5 kg",
        description_extra="Pintade entière halal pour rôtis et plats de fête.",
        ingredients="Viande de pintade (halal).",
        usage_tips="Décongeler au frais puis rôtir ou mijoter.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-DINDE-E",
        "escalopes-dinde-halal-1kg",
        "Escalopes de dinde halal",
        "1 kg — fines et polyvalentes.",
        CATEGORY_VIANDES,
        "🦃",
        10.9,
        "1 kg",
        description_extra="Escalopes de dinde halal pour poêlées, panures et plats légers.",
        ingredients="Viande de dinde (halal).",
        usage_tips="Cuire rapidement à la poêle à feu moyen.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    # —— Préparations ——
    _lf(
        "UD-MERGUEZ",
        "merguez-boeuf-halal-1kg",
        "Merguez bœuf halal",
        "1 kg — épicées, prêtes à griller.",
        CATEGORY_VIANDES,
        "🌭",
        11.9,
        "1 kg",
        description_extra="Merguez de bœuf halal pour barbecue, couscous et sandwichs.",
        ingredients="Viande de bœuf (halal), épices.",
        usage_tips="Griller ou poêler jusqu'à cuisson complète.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-KEFTA",
        "kefta-halal-1kg",
        "Kefta halal",
        "1 kg — boulettes / viande assaisonnée.",
        CATEGORY_VIANDES,
        "🧆",
        12.9,
        "1 kg",
        description_extra="Kefta halal pour brochettes, sauces tomate et plats orientaux.",
        ingredients="Viande halal, épices.",
        usage_tips="Former des boulettes ou brochettes, puis griller.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-BROCH-A",
        "brochettes-agneau-halal-1kg",
        "Brochettes d'agneau halal",
        "1 kg — déjà marinées.",
        CATEGORY_VIANDES,
        "🍢",
        19.9,
        "1 kg",
        description_extra="Brochettes d'agneau halal prêtes pour le barbecue.",
        ingredients="Viande d'agneau (halal), marinade.",
        usage_tips="Griller à feu vif en retournant régulièrement.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-BROCH-P",
        "brochettes-poulet-halal-1kg",
        "Brochettes de poulet halal",
        "1 kg — marinées, prêtes à cuire.",
        CATEGORY_VIANDES,
        "🍢",
        13.9,
        "1 kg",
        description_extra="Brochettes de poulet halal pour plancha et apéritifs.",
        ingredients="Viande de poulet (halal), marinade.",
        usage_tips="Griller ou cuire au four jusqu'à cœur.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    _lf(
        "UD-ESCAR",
        "viande-escargot-500g",
        "Viande d'escargot",
        "500–600 g — sans coque.",
        CATEGORY_VIANDES,
        "🐌",
        24.0,
        "500–600 g",
        description_extra="Viande d'escargot pour sauces et plats africains.",
        ingredients="Viande d'escargot.",
        usage_tips="Mijoter dans une sauce épicée selon la recette.",
        conservation="Surgelé — conserver à -18 °C.",
    ),
    # —— Agneau français / Pâques ——
    _lf(
        "UD-AGN-BOX-P",
        "carre-box-agneau-paques-premium",
        "Carré Box Agneau de Pâques premium",
        "Box premium 3,95–4,35 kg — pièce festive.",
        CATEGORY_VIANDES,
        "🐑",
        111.92,
        "3,95–4,35 kg",
        description_extra="Carré Box Agneau de Pâques premium. Prix à la pièce.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-BOX",
        "carre-box-agneau-paques",
        "Carré Box Agneau de Pâques",
        "Box 2,75–3,05 kg — pour les fêtes.",
        CATEGORY_VIANDES,
        "🐑",
        69.03,
        "2,75–3,05 kg",
        description_extra="Carré Box Agneau de Pâques. Prix à la pièce.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-GIG-FR",
        "gigot-agneau-francais",
        "Gigot d'agneau français",
        "2,3–2,7 kg — origine France. 38,61 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        104.25,
        "2,3–2,7 kg",
        description_extra="Gigot d'agneau français. Tarif 38,61 €/kg (max. 104,25 €/pièce). Origine nationale France.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-EPA-FR",
        "epaule-agneau-francais",
        "Épaule d'agneau français",
        "1,3–1,6 kg — origine France. 31,19 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        49.9,
        "1,3–1,6 kg",
        description_extra="Épaule d'agneau français. Tarif 31,19 €/kg (max. 49,90 €/pièce). Origine nationale France.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-C5-FR",
        "carre-5-cotes-agneau-francais",
        "Carré 5 côtes d'agneau français",
        "1–1,2 kg — origine France. 44,92 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        53.9,
        "1–1,2 kg",
        description_extra="Carré 5 côtes d'agneau français. Tarif 44,92 €/kg (max. 53,90 €/pièce). Origine nationale France.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-C8-FR",
        "carre-8-cotes-agneau-francais",
        "Carré 8 côtes d'agneau français",
        "1,2–1,6 kg — origine France. 50,00 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        80.0,
        "1,2–1,6 kg",
        description_extra="Carré 8 côtes d'agneau français. Tarif 50,00 €/kg (max. 80,00 €/pièce). Origine nationale France.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-ROT-FIC",
        "roti-epaule-agneau-ficelle",
        "Rôti d'épaule d'agneau ficelle",
        "900 g–1,2 kg — prêt à rôtir. 39,75 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        47.7,
        "900 g–1,2 kg",
        description_extra="Rôti d'épaule d'agneau ficelle. Tarif 39,75 €/kg (max. 47,70 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-ROT-NOI",
        "roti-noisette-agneau",
        "Rôti Noisette d'agneau",
        "1–1,5 kg — pièce tendre. 64,00 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        96.0,
        "1–1,5 kg",
        description_extra="Rôti Noisette d'agneau. Tarif 64,00 €/kg (max. 96,00 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-COTE-1",
        "agneau-cote-premiere",
        "Agneau côte première",
        "400–500 g — 42,24 €/kg (−20 %).",
        CATEGORY_VIANDES,
        "🐑",
        21.12,
        "400–500 g",
        description_extra="Agneau côte première. Tarif promo 42,24 €/kg (max. 21,12 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-C4",
        "carre-agneau-4-cotes-premieres",
        "Carré d'agneau 4 côtes premières",
        "400–500 g — 65,00 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        32.5,
        "400–500 g",
        description_extra="Carré d'agneau 4 côtes premières. Tarif 65,00 €/kg (max. 32,50 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-GIG-ENT",
        "gigot-agneau-entier",
        "Gigot d'agneau entier",
        "2,3–2,7 kg — 33,30 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        89.9,
        "2,3–2,7 kg",
        description_extra="Gigot d'agneau entier. Tarif 33,30 €/kg (max. 89,90 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-EPA-SP",
        "epaule-agneau-sans-palette",
        "Épaule d'agneau sans palette",
        "1,5–1,8 kg — 36,11 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        65.0,
        "1,5–1,8 kg",
        description_extra="Épaule d'agneau sans palette. Tarif 36,11 €/kg (max. 65,00 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-COT-DEC",
        "cotes-decouvertes-agneau",
        "Côtes découvertes d'agneau",
        "400–500 g — 64,00 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        32.0,
        "400–500 g",
        description_extra="Côtes découvertes d'agneau. Tarif 64,00 €/kg (max. 32,00 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-C8",
        "carre-8-cotes-agneau",
        "Carré 8 côtes d'agneau",
        "800 g–1,2 kg — 54,35 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        65.22,
        "800 g–1,2 kg",
        description_extra="Carré 8 côtes d'agneau. Tarif 54,35 €/kg (max. 65,22 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-SAU-GIG",
        "saute-gigot-agneau",
        "Sauté de gigot d'agneau",
        "800–900 g — 37,50 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        33.75,
        "800–900 g",
        description_extra="Sauté de gigot d'agneau. Tarif 37,50 €/kg (max. 33,75 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-SAU-EPA",
        "saute-epaule-agneau",
        "Sauté d'épaule d'agneau",
        "800–900 g — 35,72 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        32.15,
        "800–900 g",
        description_extra="Sauté d'épaule d'agneau. Tarif 35,72 €/kg (max. 32,15 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-NAV",
        "agneau-navarin",
        "Agneau navarin",
        "900 g–1,1 kg — 35,90 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        39.49,
        "900 g–1,1 kg",
        description_extra="Agneau navarin. Tarif 35,90 €/kg (max. 39,49 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-ROT-SEL",
        "roti-selle-agneau",
        "Rôti de selle d'agneau",
        "800 g–1 kg — 50,00 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        50.0,
        "800 g–1 kg",
        description_extra="Rôti de selle d'agneau. Tarif 50,00 €/kg (max. 50,00 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-GIGOTIN",
        "roti-gigotin-epaule-agneau",
        "Rôti Gigotin d'épaule d'agneau",
        "1,2–1,5 kg — 36,67 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        55.0,
        "1,2–1,5 kg",
        description_extra="Rôti Gigotin d'épaule d'agneau. Tarif 36,67 €/kg (max. 55,00 €/pièce).",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-ROT-EPA-FR",
        "roti-epaule-agneau-francais",
        "Rôti d'épaule d'agneau français",
        "1,3–1,7 kg — origine France. 34,41 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        58.5,
        "1,3–1,7 kg",
        description_extra="Rôti d'épaule d'agneau français. Tarif 34,41 €/kg (max. 58,50 €/pièce). Origine nationale France.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-ROT-SEL-FR",
        "roti-selle-agneau-francais",
        "Rôti de selle d'agneau français",
        "1,2–1,6 kg — origine France. 30,94 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        49.5,
        "1,2–1,6 kg",
        description_extra="Rôti de selle d'agneau français. Tarif 30,94 €/kg (max. 49,50 €/pièce). Origine nationale France.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-NAV-FR",
        "navarin-agneau-francais",
        "Navarin d'agneau français",
        "900 g–1,1 kg — origine France. 34,91 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        38.4,
        "900 g–1,1 kg",
        description_extra="Navarin d'agneau français. Tarif 34,91 €/kg (max. 38,40 €/pièce). Origine nationale France.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-AGN-COT-DEC-FR",
        "cotes-decouvertes-agneau-francais",
        "Côtes découvertes d'agneau français",
        "450–650 g — origine France. 44,00 €/kg.",
        CATEGORY_VIANDES,
        "🐑",
        28.6,
        "450–650 g",
        description_extra="Côtes découvertes d'agneau français. Tarif 44,00 €/kg (max. 28,60 €/pièce). Origine nationale France.",
        ingredients="Viande d'agneau.",
        usage_tips="Décongeler au frais si surgelé. Cuisson four, mijoté ou grillade selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    # —— Bœuf français / boxes / races ——
    _lf(
        "UD-BOE-ENT-XXL-M",
        "entrecote-xxl-boeuf-montbeliarde",
        "Entrecôte XXL de bœuf Montbéliarde",
        "350–450 g — origine France. 48,00 €/kg (−20 %).",
        CATEGORY_VIANDES,
        "🥩",
        21.6,
        "350–450 g",
        description_extra="Entrecôte XXL Montbéliarde. Tarif promo 48,00 €/kg (max. 21,60 €/pièce). Origine France.",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-COTE-FR-1",
        "cote-boeuf-france-800g-1kg",
        "Côte de bœuf origine France",
        "800 g–1 kg — origine France. 39,50 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        39.5,
        "800 g–1 kg",
        description_extra="Côte de bœuf origine France. Tarif 39,50 €/kg (max. 39,50 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-FAUX-SAL",
        "faux-filet-boeuf-salers",
        "Faux-filet de bœuf Salers",
        "300–400 g — bœuf français. 38,75 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        15.5,
        "300–400 g",
        description_extra="Faux-filet de bœuf Salers. Tarif 38,75 €/kg (max. 15,50 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ENT-CHA",
        "entrecote-boeuf-charolais",
        "Entrecôte de bœuf Charolais",
        "350–450 g — bœuf français. 43,55 €/kg (−20 %).",
        CATEGORY_VIANDES,
        "🥩",
        19.6,
        "350–450 g",
        description_extra="Entrecôte de bœuf Charolais. Tarif promo 43,55 €/kg (max. 19,60 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-BAV-X10",
        "bavette-aloyau-x10",
        "Bavette d'aloyau x10",
        "1,6–1,7 kg — lot de 10. 29,75 €/kg (−15 %).",
        CATEGORY_VIANDES,
        "🥩",
        50.58,
        "1,6–1,7 kg",
        description_extra="Bavette d'aloyau x10. Tarif promo 29,75 €/kg (max. 50,58 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-PAVE-RUM",
        "pave-rumsteck-boeuf-salers-x2",
        "Pavé de rumsteck de bœuf Salers x2",
        "300–400 g — bœuf français. 40,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        16.0,
        "300–400 g",
        description_extra="Pavé de rumsteck Salers x2. Tarif 40,00 €/kg (max. 16,00 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ENT-SEL-X2",
        "entrecote-boeuf-selection-boucher-x2",
        "Entrecôte de bœuf Sélection du Boucher x2",
        "400–600 g — 45,58 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        27.35,
        "400–600 g",
        description_extra="Entrecôte Sélection du Boucher x2. Tarif 45,58 €/kg (max. 27,35 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ENT-XXL-SEL",
        "entrecote-boeuf-xxl-selection-boucher",
        "Entrecôte de bœuf XXL Sélection du Boucher",
        "350–450 g — 40,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        18.0,
        "350–450 g",
        description_extra="Entrecôte XXL Sélection du Boucher. Tarif 40,00 €/kg (max. 18,00 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-PAL",
        "paleron-boeuf-bourguignon",
        "Paleron de bœuf pour bourguignon",
        "800–900 g — 28,44 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        25.6,
        "800–900 g",
        description_extra="Paleron de bœuf pour bourguignon. Tarif 28,44 €/kg (max. 25,60 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-TOM",
        "tomahawk-boeuf-blonde-galice",
        "Tomahawk de bœuf Blonde de Galice",
        "1–1,5 kg — origine Espagne. 79,95 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        119.93,
        "1–1,5 kg",
        description_extra="Tomahawk Blonde de Galice. Tarif 79,95 €/kg (max. 119,93 €/pièce). Origine Espagne.",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-COTE-FR-15",
        "cote-boeuf-france-1-15kg",
        "Côte de bœuf origine France",
        "1–1,5 kg — origine France. 55,90 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        83.85,
        "1–1,5 kg",
        description_extra="Côte de bœuf origine France. Tarif 55,90 €/kg (max. 83,85 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-COTE-SEL-L",
        "cote-boeuf-selection-boucher-115-14",
        "Côte de bœuf Sélection du Boucher",
        "1,15–1,4 kg — 39,90 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        55.86,
        "1,15–1,4 kg",
        description_extra="Côte de bœuf Sélection du Boucher. Tarif 39,90 €/kg (max. 55,86 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-COTE-SEL-S",
        "cote-boeuf-selection-boucher-950-115",
        "Côte de bœuf Sélection du Boucher",
        "950 g–1,15 kg — 39,90 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        45.89,
        "950 g–1,15 kg",
        description_extra="Côte de bœuf Sélection du Boucher. Tarif 39,90 €/kg (max. 45,89 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-TOUR-RUM",
        "tournedos-rumsteck-boeuf-salers-x2",
        "Tournedos de rumsteck de bœuf Salers x2",
        "300–400 g — viande de France. 44,70 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        17.88,
        "300–400 g",
        description_extra="Tournedos de rumsteck Salers x2. Tarif 44,70 €/kg (max. 17,88 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-TOUR-FIL",
        "tournedos-filet-boeuf-salers-x2",
        "Tournedos de filet de bœuf Salers x2",
        "300–400 g — viande de France. 76,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        30.4,
        "300–400 g",
        description_extra="Tournedos de filet Salers x2. Tarif 76,00 €/kg (max. 30,40 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-GITE",
        "gite-boeuf-pot-au-feu",
        "Gîte de bœuf pour pot-au-feu",
        "1,5–1,6 kg — 25,90 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        41.44,
        "1,5–1,6 kg",
        description_extra="Gîte de bœuf pour pot-au-feu. Tarif 25,90 €/kg (max. 41,44 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-FONDUE",
        "viande-fondue-boeuf-salers",
        "Viande à fondue de bœuf Salers",
        "350–450 g — origine France. 35,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        15.75,
        "350–450 g",
        description_extra="Viande à fondue Salers. Tarif 35,00 €/kg (max. 15,75 €/pièce). Origine nationale France.",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ROT-SAL-S",
        "roti-boeuf-salers-800g-1kg",
        "Rôti de bœuf Salers",
        "800 g–1 kg — bœuf français. 45,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        45.0,
        "800 g–1 kg",
        description_extra="Rôti de bœuf Salers. Tarif 45,00 €/kg (max. 45,00 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ROT-SAL-L",
        "roti-boeuf-salers-115-135",
        "Rôti de bœuf Salers",
        "1,15–1,35 kg — bœuf français. 45,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        60.75,
        "1,15–1,35 kg",
        description_extra="Rôti de bœuf Salers. Tarif 45,00 €/kg (max. 60,75 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ROT-FIL-L",
        "roti-filet-boeuf-francais-115-135",
        "Rôti de filet de bœuf français",
        "1,15–1,35 kg — origine France. 69,89 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        94.35,
        "1,15–1,35 kg",
        description_extra="Rôti de filet français. Tarif 69,89 €/kg (max. 94,35 €/pièce). Origine France.",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ROT-FIL-S",
        "roti-filet-boeuf-francais-800-900",
        "Rôti de filet de bœuf français",
        "800–900 g — origine France. 69,89 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        62.9,
        "800–900 g",
        description_extra="Rôti de filet français. Tarif 69,89 €/kg (max. 62,90 €/pièce). Origine France.",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ROT-TEN-XL",
        "roti-boeuf-tende-tranche-2-22",
        "Rôti de bœuf tende de tranche",
        "2–2,2 kg — 33,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        72.6,
        "2–2,2 kg",
        description_extra="Rôti tende de tranche. Tarif 33,00 €/kg (max. 72,60 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ROT-TEN-M",
        "roti-boeuf-tende-tranche-115-135",
        "Rôti de bœuf tende de tranche",
        "1,15–1,35 kg — 33,95 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        45.83,
        "1,15–1,35 kg",
        description_extra="Rôti tende de tranche. Tarif 33,95 €/kg (max. 45,83 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ROT-TEN-S",
        "roti-boeuf-tende-tranche-800g-1kg",
        "Rôti de bœuf tende de tranche",
        "800 g–1 kg — 29,90 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        29.9,
        "800 g–1 kg",
        description_extra="Rôti tende de tranche. Tarif 29,90 €/kg (max. 29,90 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-TART",
        "steak-tartare-boeuf-francais-180g",
        "Steak tartare de bœuf français 5% MG",
        "180 g — bœuf français. 5,76 €/pièce.",
        CATEGORY_VIANDES,
        "🥩",
        5.76,
        "180 g",
        description_extra="Steak tartare français 5 % MG. Prix 5,76 €/pièce (32,00 €/kg).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ONG",
        "onglet-boeuf-x2",
        "Onglet de bœuf x2",
        "300–400 g — 41,50 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        16.6,
        "300–400 g",
        description_extra="Onglet de bœuf x2. Tarif 41,50 €/kg (max. 16,60 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-POIRE",
        "steak-poire-boeuf-x2",
        "Steak de poire de bœuf x2",
        "300–400 g — 29,75 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        11.9,
        "300–400 g",
        description_extra="Steak de poire x2. Tarif 29,75 €/kg (max. 11,90 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-BAV-X2",
        "bavette-aloyau-x2",
        "Bavette d'aloyau x2",
        "300–400 g — 35,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        14.0,
        "300–400 g",
        description_extra="Bavette d'aloyau x2. Tarif 35,00 €/kg (max. 14,00 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-EMIN",
        "emince-boeuf-500g",
        "Émincé de bœuf",
        "±500 g — 24,22 €/kg (−10 %).",
        CATEGORY_VIANDES,
        "🥩",
        13.32,
        "±500 g",
        description_extra="Émincé de bœuf. Tarif promo 24,22 €/kg (max. 13,32 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-BOX-100",
        "carre-box-boeuf-100",
        "Carré Box 100% bœuf",
        "3,85–4,85 kg — box familiale (−10 %).",
        CATEGORY_VIANDES,
        "🥩",
        169.05,
        "3,85–4,85 kg",
        description_extra="Carré Box 100 % bœuf. Prix 169,05 €/pièce (−10 %).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-BOX-PROT-R",
        "carre-box-regime-proteine-rotis",
        "Carré Box régime protéiné avec rôtis",
        "4–5,1 kg — box protéinée (−10 %).",
        CATEGORY_VIANDES,
        "🥩",
        164.21,
        "4–5,1 kg",
        description_extra="Carré Box régime protéiné avec rôtis. Prix 164,21 €/pièce (−10 %).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-BOX-FAM",
        "carre-box-viande-famille-nombreuse",
        "Carré Box viande famille nombreuse",
        "6,2–6,9 kg — grande famille (−10 %).",
        CATEGORY_VIANDES,
        "🥩",
        158.49,
        "6,2–6,9 kg",
        description_extra="Carré Box viande famille nombreuse. Prix 158,49 €/pièce (−10 %).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-BOX-DEG",
        "carre-box-degustation-plaisir",
        "Carré Box dégustation plaisir",
        "3–4 kg — dégustation (−10 %).",
        CATEGORY_VIANDES,
        "🥩",
        127.16,
        "3–4 kg",
        description_extra="Carré Box dégustation plaisir. Prix 127,16 €/pièce (−10 %).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-BOX-AUTH",
        "carre-box-viande-familial-authentique",
        "Carré Box viande familial authentique",
        "4,8–7 kg — box familiale (−10 %).",
        CATEGORY_VIANDES,
        "🥩",
        113.86,
        "4,8–7 kg",
        description_extra="Carré Box viande familial authentique. Prix 113,86 €/pièce (−10 %).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-BOX-PROT",
        "carre-box-regime-proteine",
        "Carré Box régime protéiné",
        "3,7–5 kg — box protéinée (−10 %).",
        CATEGORY_VIANDES,
        "🥩",
        138.38,
        "3,7–5 kg",
        description_extra="Carré Box régime protéiné. Prix 138,38 €/pièce (−10 %).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ENT-FR-XXL",
        "entrecote-boeuf-francaise-xxl",
        "Entrecôte de bœuf française XXL",
        "350–450 g — origine France. 50,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        22.5,
        "350–450 g",
        description_extra="Entrecôte française XXL. Tarif 50,00 €/kg (max. 22,50 €/pièce). Origine France.",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ENT-FR",
        "entrecote-boeuf-francaise",
        "Entrecôte de bœuf française",
        "250–350 g — origine France. 50,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        17.5,
        "250–350 g",
        description_extra="Entrecôte française. Tarif 50,00 €/kg (max. 17,50 €/pièce). Origine France.",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-FIL-ENT",
        "filet-boeuf-entier",
        "Filet de bœuf entier",
        "1,5–2,5 kg — 63,96 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        159.9,
        "1,5–2,5 kg",
        description_extra="Filet de bœuf entier. Tarif 63,96 €/kg (max. 159,90 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-FIL-FR",
        "filet-boeuf-francais-entier",
        "Filet de bœuf français entier",
        "1,6–2 kg — origine France. 61,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        122.0,
        "1,6–2 kg",
        description_extra="Filet de bœuf français entier. Tarif 61,00 €/kg (max. 122,00 €/pièce). Origine France.",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-COTE-ANG",
        "cote-boeuf-angus",
        "Côte de bœuf Angus",
        "950 g–1,15 kg — 60,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        69.0,
        "950 g–1,15 kg",
        description_extra="Côte de bœuf Angus. Tarif 60,00 €/kg (max. 69,00 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-PIC",
        "picanha-boeuf-angus",
        "Picanha de bœuf Angus",
        "1,5–2,5 kg — 39,90 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        99.75,
        "1,5–2,5 kg",
        description_extra="Picanha de bœuf Angus. Tarif 39,90 €/kg (max. 99,75 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-FIL-ANG",
        "filet-boeuf-angus-entier",
        "Filet de bœuf Angus entier",
        "1,5–2,5 kg — 72,90 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        182.25,
        "1,5–2,5 kg",
        description_extra="Filet de bœuf Angus entier. Tarif 72,90 €/kg (max. 182,25 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ENT-WAG",
        "entrecote-boeuf-wagyu-japonais",
        "Entrecôte de bœuf Wagyu japonais",
        "200–250 g — origine Japon. 239,60 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        59.9,
        "200–250 g",
        description_extra="Entrecôte Wagyu japonais. Tarif 239,60 €/kg (max. 59,90 €/pièce). Origine Japon.",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ONG-ANG",
        "onglet-boeuf-angus-x2",
        "Onglet de bœuf Angus x2",
        "300–400 g — 46,25 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        18.5,
        "300–400 g",
        description_extra="Onglet de bœuf Angus x2. Tarif 46,25 €/kg (max. 18,50 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ENT-XXL-SAL",
        "entrecote-xxl-boeuf-salers",
        "Entrecôte XXL de bœuf Salers",
        "350–450 g — bœuf français. 59,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        26.55,
        "350–450 g",
        description_extra="Entrecôte XXL Salers. Tarif 59,00 €/kg (max. 26,55 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
    _lf(
        "UD-BOE-ENT-SAL",
        "entrecote-boeuf-salers",
        "Entrecôte de bœuf Salers",
        "250–350 g — bœuf français. 59,00 €/kg.",
        CATEGORY_VIANDES,
        "🥩",
        20.65,
        "250–350 g",
        description_extra="Entrecôte Salers. Tarif 59,00 €/kg (max. 20,65 €/pièce).",
        ingredients="Viande de bœuf.",
        usage_tips="Décongeler au frais si surgelé. Grillade, poêle ou four selon la coupe.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
]

LABELAFRIK_EXTRA = [
    _lf(
        "UD-MOR-F",
        "moringa-feuilles-poudre-100g",
        "Poudre de feuilles de moringa",
        "Riche en nutriments et antioxydants.",
        CATEGORY_CONDIMENTS,
        "🌿",
        3.5,
        "100 g",
        description_extra="Boissons, compléments et cuisine santé.",
    ),
    _lf(
        "UD-MIEL-5",
        "miel-fleurs-500g",
        "Miel de fleurs",
        "Naturel et savoureux — pot 500 g.",
        CATEGORY_MIELS,
        "🍯",
        5,
        "500 g",
    ),
    # —— Huile fondue ——
    _lf(
        "UD-HUILE-FONDUE",
        "huile-speciale-fondue-1l",
        "Huile spéciale fondue",
        "Bouteille verre 1 L — origine France.",
        CATEGORY_HUILES,
        "🫒",
        9.9,
        "1 L",
        description_extra="Huile spéciale fondue. Prix 9,90 €/pièce (9,00 €/kg). Origine nationale France.",
        ingredients="Huile végétale.",
        usage_tips="Utiliser pour fondue bourguignonne selon notice.",
        conservation="Au frais ou surgelé selon lot — respecter la DLC / DDM.",
    ),
]

LABELAFRIK_CATALOGUE = (
    LABELAFRIK_PHARES
    + LABELAFRIK_RIZ
    + LABELAFRIK_FARINES
    + LABELAFRIK_HUILES
    + LABELAFRIK_BOISSONS
    + LABELAFRIK_SNACKS
    + LABELAFRIK_SNACKS_EXTRA
    + LABELAFRIK_LEGUMES
    + LABELAFRIK_CONDIMENTS
    + LABELAFRIK_FRUITS
    + LABELAFRIK_ALIMENTS
    + LABELAFRIK_CONSERVES
    + LABELAFRIK_MER
    + LABELAFRIK_VIANDES
    + LABELAFRIK_EXTRA
)

LABELAFRIK_SLUGS = frozenset(
    list(LABELAFRIK_UPDATES.keys()) + [p["slug"] for p in LABELAFRIK_CATALOGUE]
)
