# -*- coding: utf-8 -*-
"""Catalogue produits sénégalais — extension Yombal Marché."""

from models.constants import (
    CATEGORY_BOISSONS,
    CATEGORY_CEREALES,
    CATEGORY_CONDIMENTS,
    CATEGORY_CONSERVES,
    CATEGORY_FRUITS_SECS,
    CATEGORY_HUILES,
    CATEGORY_LEGUMINEUSES,
    CATEGORY_SNACKS,
)


def _item(
    sku,
    slug,
    name,
    summary,
    category,
    icon,
    price_cents,
    weight_info,
    *,
    origin="Sénégal — terroir local",
    ingredients="",
    allergens="",
    usage_tips="",
    conservation="À l'abri de la lumière et de l'humidité.",
    description_extra="",
):
    desc = (
        f"{summary}\n\n"
        f"Sélection Yombal Marché issue de circuits courts et de producteurs partenaires au Sénégal "
        f"et en diaspora.\n\n"
        f"{description_extra}"
    ).strip()
    return {
        "sku": sku,
        "slug": slug,
        "name": name,
        "summary": summary,
        "description": desc,
        "price_cents": price_cents,
        "category": category,
        "icon": icon,
        "origin": origin,
        "weight_info": weight_info,
        "ingredients": ingredients,
        "allergens": allergens,
        "usage_tips": usage_tips,
        "conservation": conservation,
    }


EXTENDED_CATALOGUE = [
    # —— Boissons ——
    _item(
        "BOIS-BISSAP-SEC-200",
        "bissap-seche-200g",
        "Bissap séché",
        "Fleurs d'hibiscus pour tisane ou jus rouge.",
        CATEGORY_BOISSONS,
        "🌺",
        490,
        "200 g — sachet",
        ingredients="Fleurs d'hibiscus séchées (bissap) 100 %.",
        usage_tips="Infuser 2 c. à soupe dans 1 L d'eau bouillante 10 min. Sucre et menthe au goût.",
    ),
    _item(
        "BOIS-GINGEMBRE-100",
        "gingembre-poudre-100g",
        "Gingembre en poudre",
        "Épice chaude et piquante, séchée localement.",
        CATEGORY_BOISSONS,
        "🫚",
        450,
        "100 g — pot",
        ingredients="Gingembre séché moulu.",
        usage_tips="Dans les jus de bissap, thés ou marinades. Commencer par une pincée.",
    ),
    _item(
        "BOIS-BOUYE-250",
        "bouye-baobab-250g",
        "Bouye (pain de singe)",
        "Pulpe de baobab en poudre, très nutritive.",
        CATEGORY_BOISSONS,
        "🌳",
        690,
        "250 g — sachet",
        ingredients="Pulpe de fruit de baobab déshydratée.",
        usage_tips="Mélanger à l'eau, lait ou jus pour une boisson énergisante. Idéal en smoothie.",
    ),
    _item(
        "BOIS-DITAKH-300",
        "ditakh-300g",
        "Ditakh",
        "Fruit du ditakhier pour boissons rafraîchissantes.",
        CATEGORY_BOISSONS,
        "🍋",
        590,
        "300 g — pulpe séchée",
        ingredients="Pulpe de ditakh déshydratée.",
        usage_tips="Réhydrater et passer au chinois pour un jus acidulé très rafraîchissant.",
    ),
    _item(
        "BOIS-KINKELIBA-80",
        "kinkeliba-80g",
        "Kinkeliba",
        "Feuilles séchées pour tisane digestive.",
        CATEGORY_BOISSONS,
        "🍃",
        420,
        "80 g — sachet",
        ingredients="Feuilles de Combretum micranthum séchées.",
        usage_tips="Infusion 5 à 8 min, 1 poignée pour 1 L. Consommation du soir recommandée.",
    ),
    _item(
        "BOIS-CAFE-TOUBA-250",
        "cafe-touba-250g",
        "Café Touba",
        "Café épicé au diar, spécialité mouride.",
        CATEGORY_BOISSONS,
        "☕",
        850,
        "250 g — moulu",
        ingredients="Café torréfié, grains de diar (Selim).",
        usage_tips="Préparer en filtre ou bouilloire. Parfumé et légèrement poivré.",
    ),
    _item(
        "BOIS-TAMARIN-200",
        "tamarin-pulpe-200g",
        "Tamarin (tamarin)",
        "Pulpe acidulée pour jus et sauces.",
        CATEGORY_BOISSONS,
        "🍫",
        520,
        "200 g — bloc",
        ingredients="Pulpe de tamarinier, sans additifs.",
        usage_tips="Diluer dans l'eau pour un jus, ou incorporer aux sauces et marinades.",
    ),
    # —— Céréales ——
    _item(
        "CER-RIZ-1KG",
        "riz-brise-local-1kg",
        "Riz brisé local",
        "Riz cultivé dans la vallée du fleuve Sénégal.",
        CATEGORY_CEREALES,
        "🌾",
        550,
        "1 kg",
        ingredients="Riz brisé 100 %.",
        usage_tips="Parfait pour le thiéboudienne et les riz gras. Rincer avant cuisson.",
    ),
    _item(
        "CER-MIL-1KG",
        "mil-millet-1kg",
        "Mil (millet)",
        "Céréale de base, base du thiéré et du fondé.",
        CATEGORY_CEREALES,
        "🌿",
        480,
        "1 kg",
        ingredients="Mil décortiqué.",
        usage_tips="Cuire en bouillie ou couscous de mil. Tremper 2 h pour un fondé onctueux.",
    ),
    _item(
        "CER-SORGHO-1KG",
        "sorgho-1kg",
        "Sorgho",
        "Céréale rustique cultivée en zone sèche.",
        CATEGORY_CEREALES,
        "🌱",
        460,
        "1 kg",
        ingredients="Sorgho.",
        usage_tips="Bouillies, couscous ou mélange avec le mil.",
    ),
    _item(
        "CER-FONIO-500",
        "fonio-500g",
        "Fonio",
        "Ancienne céréale sans gluten, goût délicat.",
        CATEGORY_CEREALES,
        "✨",
        790,
        "500 g",
        ingredients="Fonio (Digitaria exilis).",
        allergens="Sans gluten (selon préparation industrielle — vérifier le lot).",
        usage_tips="Cuisson rapide 5 min à la vapeur. Accompagne poissons et sauces.",
    ),
    _item(
        "CER-MAIS-1KG",
        "mais-concasse-1kg",
        "Maïs concassé",
        "Maïs local moulu pour couscous et bouillies.",
        CATEGORY_CEREALES,
        "🌽",
        440,
        "1 kg",
        ingredients="Maïs concassé.",
        usage_tips="Bouillie sucrée ou salée. Cuisson lente à couvert avec remontée d'eau.",
    ),
    _item(
        "CER-NIEbe-FAR-500",
        "farine-niebe-500g",
        "Farine de niébé",
        "Farine de haricot local pour beignets et galettes.",
        CATEGORY_CEREALES,
        "🫘",
        520,
        "500 g",
        ingredients="Farine de niébé (Vigna unguiculata).",
        usage_tips="Base des beignets akara et galettes. Mélanger avec eau, oignon et épices.",
    ),
    # —— Condiments ——
    _item(
        "CON-SOUMBALA-100",
        "soumbala-100g",
        "Soumbala",
        "Condiment fermenté de néré, umami africain.",
        CATEGORY_CONDIMENTS,
        "🧄",
        580,
        "100 g — boules séchées",
        ingredients="Graines de néré fermentées (Parkia biglobosa).",
        usage_tips="Émietter dans les sauces de viande, poisson ou légumes en fin de cuisson.",
    ),
    _item(
        "CON-NETETOU-100",
        "netetou-100g",
        "Nététou (fermenté)",
        "Graines de néré fermentées, très aromatiques.",
        CATEGORY_CONDIMENTS,
        "🫙",
        590,
        "100 g",
        ingredients="Nététou fermenté.",
        usage_tips="Indispensable au thiéboudienne rouge. Ajouter en fin de cuisson.",
    ),
    _item(
        "CON-YETT-150",
        "yett-coquillages-150g",
        "Yett (coquillages séchés)",
        "Coquillages séchés pour bouillons et sauces.",
        CATEGORY_CONDIMENTS,
        "🐚",
        750,
        "150 g",
        ingredients="Coquillages séchés.",
        allergens="Mollusques.",
        usage_tips="Rincer, faire tremper puis cuire longuement dans le bouillon de thiéboudienne.",
    ),
    _item(
        "CON-PIMENT-80",
        "piment-sec-moulu-80g",
        "Piment séché moulu",
        "Piment local séché et réduit en poudre.",
        CATEGORY_CONDIMENTS,
        "🌶",
        380,
        "80 g — pot",
        ingredients="Piment séché moulu.",
        usage_tips="Dosage progressif — très fort. Pour yassa, mafé et marinades.",
    ),
    _item(
        "CON-KETIAKH-100",
        "ketiakh-poisson-100g",
        "Kétiakh (poisson fermenté)",
        "Poisson fermenté très puissant en goût.",
        CATEGORY_CONDIMENTS,
        "🐟",
        680,
        "100 g",
        ingredients="Poisson fermenté et séché.",
        allergens="Poisson.",
        usage_tips="Utiliser en petite quantité pour relever les sauces. Bien aérer la cuisine.",
    ),
    _item(
        "CON-SEL-KAOLACK-500",
        "sel-kaolack-500g",
        "Sel de Kaolack",
        "Sel de mer artisanal extrait des salines.",
        CATEGORY_CONDIMENTS,
        "🧂",
        290,
        "500 g",
        ingredients="Sel de mer.",
        usage_tips="Assaisonnement et conservation des arachides grillées.",
    ),
    _item(
        "CON-YASSA-60",
        "epices-yassa-60g",
        "Mélange épices yassa",
        "Blend d'épices pour yassa poulet traditionnel.",
        CATEGORY_CONDIMENTS,
        "🫙",
        490,
        "60 g — sachet",
        ingredients="Oignon déshydraté, moutarde, piment, ail, citron, épices.",
        usage_tips="Mariner le poulet 2 h minimum avant cuisson à la poêle.",
    ),
    # —— Huiles ——
    _item(
        "HUI-ARACHIDE-1L",
        "huile-arachide-1l",
        "Huile d'arachide",
        "Extraite à froid d'arachides locales du Sine-Saloum.",
        CATEGORY_HUILES,
        "🫒",
        1190,
        "1 L — bouteille",
        ingredients="Huile d'arachide vierge.",
        allergens="Arachides.",
        usage_tips="Friture et cuisson des plats sénégalais. Goût de cacahuète léger.",
    ),
    _item(
        "HUI-SESAME-250",
        "huile-sesame-250ml",
        "Huile de sésame",
        "Huile artisanale au goût de noisette prononcé.",
        CATEGORY_HUILES,
        "🌰",
        990,
        "250 ml",
        ingredients="Huile de sésame pressée à froid.",
        allergens="Sésame.",
        usage_tips="Assaisonnement cru sur salades et marinades.",
    ),
    _item(
        "HUI-KARITE-ALIM-250",
        "beurre-karite-alimentaire-250g",
        "Beurre de karité alimentaire",
        "Karité du Sénégal oriental pour cuisine traditionnelle.",
        CATEGORY_HUILES,
        "🧈",
        890,
        "250 g — pot",
        ingredients="Beurre de karité pur (alimentaire).",
        usage_tips="En fin de cuisson du thiéré ou pour enrichir les bouillies.",
        description_extra="À distinguer du beurre de karité cosmétique : celui-ci est destiné à la cuisine.",
    ),
    _item(
        "HUI-MORINGA-100",
        "huile-moringa-100ml",
        "Huile de moringa",
        "Extraite des graines de l'arbre miracle.",
        CATEGORY_HUILES,
        "💚",
        1490,
        "100 ml",
        ingredients="Huile de Moringa oleifera.",
        usage_tips="Assaisonnement fin ou soin capillaire selon usage.",
    ),
    # —— Snacks & Desserts ——
    _item(
        "SNK-THIAKRY-400",
        "thiakry-400g",
        "Thiakry",
        "Couscous de mil sucré avec yaourt, dessert populaire.",
        CATEGORY_SNACKS,
        "🍮",
        650,
        "400 g — kit (semoule + épices)",
        ingredients="Semoule de mil, sucre vanillé, raisins secs (selon lot).",
        allergens="Peut contenir gluten selon préparation.",
        usage_tips="Humidifier la semoule, mélanger au yaourt sucré. Servir frais.",
    ),
    _item(
        "SNK-NGALAKH-350",
        "ngalakh-350g",
        "Ngalakh",
        "Dessert de mil, beurre de baobab et cacahuètes.",
        CATEGORY_SNACKS,
        "🥣",
        720,
        "350 g — préparation sèche",
        ingredients="Mil, poudre de baobab, arachides, sucre.",
        allergens="Arachides.",
        usage_tips="Réhydrater selon notice et laisser reposer au frais.",
    ),
    _item(
        "SNK-AKARA-300",
        "akara-mix-300g",
        "Beignets de niébé (akara) — mix",
        "Base de farine et épices pour akara maison.",
        CATEGORY_SNACKS,
        "🟤",
        540,
        "300 g",
        ingredients="Farine de niébé, oignon déshydraté, piment, sel.",
        usage_tips="Ajouter eau, mixer, frire en beignets dorés.",
    ),
    _item(
        "SNK-GALETTE-MIL-400",
        "galettes-mil-400g",
        "Galettes de mil",
        "Pain plat traditionnel cuit à la braise.",
        CATEGORY_SNACKS,
        "🫓",
        480,
        "400 g — 4 pièces sous vide",
        ingredients="Farine de mil, eau, sel.",
        usage_tips="Réchauffer à la poêle ou au four. Servir avec sauce ou thiéré.",
    ),
    _item(
        "SNK-TAMARIN-PAST-150",
        "pastilles-tamarin-150g",
        "Pastilles de tamarin",
        "Bonbons artisanaux au tamarin et piment.",
        CATEGORY_SNACKS,
        "🍬",
        390,
        "150 g — sachet",
        ingredients="Tamarin, sucre, piment.",
        usage_tips="Collation acidulée-piquante.",
    ),
    _item(
        "SNK-ARACHIDE-300",
        "arachides-grillees-300g",
        "Arachides grillées salées",
        "Cacahuètes rôties au sel de Kaolack.",
        CATEGORY_SNACKS,
        "🥜",
        420,
        "300 g",
        ingredients="Arachides, sel.",
        allergens="Arachides.",
        usage_tips="Apéritif ou croquant dans les salades.",
    ),
    # —— Conserves ——
    _item(
        "CONS-GUEDJ-200",
        "guedj-poisson-200g",
        "Guedj (poisson séché)",
        "Mulet séché et fumé, base de nombreux plats.",
        CATEGORY_CONSERVES,
        "🐡",
        890,
        "200 g",
        ingredients="Poisson séché et fumé.",
        allergens="Poisson.",
        usage_tips="Nettoyer, tremper puis incorporer aux sauces tomate ou gombo.",
    ),
    _item(
        "CONS-TOMATE-400",
        "tomate-concentree-400g",
        "Tomate concentrée artisanale",
        "Concentré de tomates locales, sans conservateurs.",
        CATEGORY_CONSERVES,
        "🍅",
        490,
        "400 g — pot verre",
        ingredients="Tomates concentrées.",
        usage_tips="Base des sauces pour riz, pâtes et poissons.",
    ),
    _item(
        "CONS-LEG-THIEB-200",
        "legumes-seches-thiebou-200g",
        "Légumes séchés (mix thiébou)",
        "Manioc, aubergine, gombo séchés pour le riz.",
        CATEGORY_CONSERVES,
        "🥦",
        560,
        "200 g — mélange",
        ingredients="Légumes déshydratés (manioc, aubergine, gombo).",
        usage_tips="Réhydrater 30 min puis cuire avec le riz et la sauce.",
    ),
    _item(
        "CONS-CREVETTE-100",
        "crevettes-sechees-100g",
        "Crevettes séchées",
        "Crevettes de Saint-Louis séchées au soleil.",
        CATEGORY_CONSERVES,
        "🦐",
        980,
        "100 g",
        ingredients="Crevettes séchées.",
        allergens="Crustacés.",
        usage_tips="Piler ou infuser pour un bouillon umami. Parfait pour le thiéboudienne.",
    ),
    _item(
        "CONS-CONF-BISSAP-250",
        "confiture-bissap-250g",
        "Confiture de bissap",
        "Confiture d'hibiscus artisanale sucrée.",
        CATEGORY_CONSERVES,
        "🫙",
        590,
        "250 g — pot",
        ingredients="Fleurs de bissap, sucre, citron.",
        usage_tips="Sur tartines, yaourt ou fromage frais.",
    ),
    _item(
        "CONS-PUREE-ARACHIDE-350",
        "puree-arachide-350g",
        "Purée d'arachide (thiakry)",
        "Beurre de cacahuète 100 % local.",
        CATEGORY_CONSERVES,
        "🥜",
        650,
        "350 g — pot",
        ingredients="Arachides grillées.",
        allergens="Arachides.",
        usage_tips="Enrichir le thiakry ou tartiner.",
    ),
    # —— Légumineuses ——
    _item(
        "LEG-NIEbe-1KG",
        "niebe-haricot-1kg",
        "Niébé (haricot local)",
        "Haricot à œil noir, riche en protéines végétales.",
        CATEGORY_LEGUMINEUSES,
        "🫘",
        520,
        "1 kg",
        ingredients="Niébé sec.",
        usage_tips="Tremper une nuit, cuire longuement pour plats en sauce.",
    ),
    _item(
        "LEG-LENTILLE-500",
        "lentilles-locales-500g",
        "Lentilles locales",
        "Légumineuses cultivées dans la vallée du fleuve.",
        CATEGORY_LEGUMINEUSES,
        "🟤",
        480,
        "500 g",
        ingredients="Lentilles.",
        usage_tips="Cuisson 25–35 min sans trempage. Salade ou sauce.",
    ),
    _item(
        "LEG-SESAME-250",
        "graine-sesame-250g",
        "Graine de sésame",
        "Sésame blanc ou noir, riche en calcium.",
        CATEGORY_LEGUMINEUSES,
        "⚪",
        440,
        "250 g",
        ingredients="Graines de sésame.",
        allergens="Sésame.",
        usage_tips="Torréfier légèrement et saupoudrer sur plats ou pâtisserie.",
    ),
    # —— Fruits séchés ——
    _item(
        "FRU-MANGUE-150",
        "mangue-sechee-150g",
        "Mangue séchée",
        "Tranches de mangue locale séchée naturellement.",
        CATEGORY_FRUITS_SECS,
        "🥭",
        590,
        "150 g",
        ingredients="Mangue séchée.",
        usage_tips="Collation ou décoration desserts.",
    ),
    _item(
        "FRU-PLANTAIN-120",
        "banane-plantain-sechee-120g",
        "Banane plantain séchée",
        "Chips de plantain de Casamance, sans additifs.",
        CATEGORY_FRUITS_SECS,
        "🍌",
        450,
        "120 g",
        ingredients="Plantain, huile de palme ou tournesol (selon lot), sel.",
        usage_tips="Snack croustillant.",
    ),
    _item(
        "FRU-MORINGA-100",
        "moringa-poudre-100g",
        "Moringa en poudre",
        "Poudre de feuilles de moringa, super-aliment.",
        CATEGORY_FRUITS_SECS,
        "🌿",
        690,
        "100 g — sachet",
        ingredients="Feuilles de moringa séchées et broyées.",
        usage_tips="1 c. à café dans jus, smoothies ou sauces.",
    ),
]
