# -*- coding: utf-8 -*-
"""
Noms d'affichage boutique — convention : « Produit — conditionnement ».
Le conditionnement reprend weight_info (sans texte emballage).
"""

# Noms complets par slug (prioritaires)
PRODUCT_DISPLAY_NAMES = {
    # —— Catalogue initial ——
    "couscous-complet-1kg": "Couscous complet — 1 kg",
    "huile-argan-bio-100ml": "Huile d'argan bio — 100 ml",
    "miel-thym-500g": "Miel d'acacia — 500 g",
    "cafe-arabica-250g": "Café arabica — 250 g",
    "savon-noir-eucalyptus": "Savon noir eucalyptus — 200 g",
    "beurre-karite-brut-150g": "Beurre de karité — 150 g",
    "huile-palme-artisanale-1l": "Huile de palme artisanale — 1 L",
    # —— Extension terroir ——
    "bissap-seche-200g": "Bissap séché — 200 g",
    "gingembre-poudre-100g": "Gingembre — 100 g",
    "bouye-baobab-250g": "Baobab — 250 g",
    "ditakh-300g": "Ditakh — 300 g",
    "kinkeliba-80g": "Kinkeliba — 80 g",
    "cafe-touba-250g": "Café Touba — 250 g",
    "tamarin-pulpe-200g": "Dakhar — 200 g",
    "mil-millet-1kg": "Mil — 1 kg",
    "sorgho-1kg": "Sorgho — 1 kg",
    "fonio-500g": "Fonio — 500 g",
    "soumbala-100g": "Soumbala — 100 g",
    "netetou-100g": "Nététou — 100 g",
    "yett-coquillages-150g": "Yett — 150 g",
    "piment-sec-moulu-80g": "Piment moulu — 80 g",
    "sel-kaolack-500g": "Sel de Kaolack — 500 g",
    "beurre-karite-alimentaire-250g": "Beurre de karité alimentaire — 250 g",
    # —— Desserts ——
    "thiakry-400g": "Thiakhry — 400 g",
    "sombi-riz-au-lait": "Riz au lait (sombi) — 400 g",
    "thiakhri-au-lait": "Thiakhri au lait — 400 g",
    "thiakhri-ngalakh": "Thiakhri pâte d'arachide (ngalakh) — 400 g",
    "legumes-seches-thiebou-200g": "Légumes séchés thiéb — 200 g",
    "crevettes-sechees-100g": "Crevettes séchées — 100 g",
    "graine-sesame-250g": "Graines de sésame — 250 g",
    # —— LabelAfrik phares ——
    "arraw-mil-labelafrik": "Arraw — 500 g",
    "sankhal-labelafrik": "Sankhal — 500 g",
    "thiere-lalo-labelafrik": "Thiéré lalo — 500 g",
    "soungouf-labelafrik": "Soungouf — 500 g",
    "moringa-poudre-labelafrik": "Moringa — 100 g",
    "gombo-poudre-labelafrik": "Gombo — 100 g",
    "pate-arachide-labelafrik": "Pâte d'arachide — 500 g",
    # —— Riz ——
    "riz-long-parfume-20kg": "Riz long parfumé — 20 kg",
    "riz-brise-2x-20kg": "Riz brisé (2×) — 20 kg",
    "riz-brise-1x-20kg": "Riz brisé (1×) — 20 kg",
    "riz-long-parfume-45kg": "Riz long parfumé — 4,5 kg",
    "riz-brise-1x-5kg": "Riz brisé (1×) — 5 kg",
    "riz-brise-2x-5kg": "Riz brisé (2×) — 5 kg",
    "riz-long-parfume-thai-1kg": "Riz long parfumé thaï — 1 kg",
    "riz-long-parfume-1kg": "Riz long parfumé — 1 kg",
    "riz-brise-2x-1kg": "Riz brisé (2×) — 1 kg",
    "riz-casse-1x-1kg": "Riz cassé (1×) — 1 kg",
    "riz-casse-2x-1kg": "Riz cassé (2×) — 1 kg",
    # —— Farines & céréales ——
    "farine-riz-1kg": "Farine de riz — 1 kg",
    "farine-mil-1kg": "Farine de mil — 1 kg",
    "farine-manioc-1kg": "Farine de manioc — 1 kg",
    "fecule-pomme-de-terre-1kg": "Fécule de pomme de terre — 1 kg",
    "farine-mais-jaune": "Farine de maïs jaune — 1 kg",
    "farine-mais-blanc": "Farine de maïs blanc — 1 kg",
    "grain-de-mil": "Grains de mil — 1 kg",
    "foufou-farine-manioc": "Foufou — 500 g",
    "fufu-farine-plantain": "Fufu plantain — 600 g",
    "fiono-guinee": "Fiono — 500 g",
    # —— Huiles ——
    "huile-tournesol-1l": "Huile de tournesol — 1 L",
    "huile-arachide-1l": "Huile d'arachide — 1 L",
    "huile-tournesol-5l": "Huile de tournesol — 5 L",
    "huile-palme-1l": "Huile de palme — 1 L",
    "butter-ghee": "Beurre ghee — 500 g",
    # —— Boissons ——
    "sirop-bissap-ud": "Sirop de bissap — 50 cl",
    "sirop-gingembre-ud": "Sirop de gingembre — 50 cl",
    "boisson-gingembre-ud": "Boisson au gingembre — 1 L",
    "bissap-rouge-vrac-1kg": "Bissap rouge — 1 kg",
    "poudre-baobab-zena-200g": "Baobab Zena — 200 g",
    "miel-fleurs-1kg": "Miel de fleurs — 1 kg",
    "lait-coco-ud": "Lait de coco — 400 ml",
    "bissap-rouge-zena": "Bissap blanc Zena — 125 g",
    "poudre-lait-nido-400g": "Lait en poudre Nido — 400 g",
    "poudre-lait-nido-900g": "Lait en poudre Nido — 900 g",
    "poudre-lait-nido-1800g": "Lait en poudre Nido — 1,8 kg",
    "poudre-lait-nido-2500g": "Lait en poudre Nido — 2,5 kg",
    "the-instantane-starling": "Thé instantané Starling",
    "boisson-instantanee-foster": "Boisson instantanée Foster",
    # —— Snacks ——
    "chips-plantain-doux": "Chips de plantain — doux",
    "chips-plantain-epice": "Chips de plantain — épicé",
    "chips-plantain-sale": "Chips de plantain — salé",
    "biscuits-gem": "Biscuits Gem",
    "samoussas-legumes-halal": "Samoussas légumes — 20 pièces",
    "samoussas-poulet-20": "Samoussas poulet — 20 pièces",
    "samoussas-mouton-halal": "Samoussas mouton — 20 pièces",
    "accras-morue": "Accras de morue",
    "nems-poulet-halal-50": "Nems poulet — 50 pièces",
    "nems-crevettes-poulet-halal": "Nems crevettes & poulet — 50 pièces",
    "fataya-poisson-10": "Fataya poisson — 10 pièces",
    "fataya-viande-10": "Fataya viande — 10 pièces",
    # —— Desserts ——
    "thiacry-de-mil": "Thiakhry (préparation) — 400 g",
    # —— Légumineuses ——
    "cornilles-haricots-blancs": "Cornilles — 500 g",
    "haricots-noirs-tersol": "Haricots noirs Tersol — 500 g",
    "arachides-crues-blanches-1kg": "Arachides crues — 1 kg",
    "farine-niebe-500g": "Farine de niébé — 500 g",
    # —— Condiments ——
    "poudre-arachide-ud": "Poudre d'arachide — 500 g",
    "pate-arachide-dakatine": "Pâte d'arachide Dakatine",
    "piment-rouge-antillais": "Piment antillais fort",
    "bouillon-adjia": "Bouillon Adjia",
    "jumbo-ramadan": "Bouillon Jumbo Ramadan",
    "pate-arachide-25kg": "Pâte d'arachide — 2,5 kg",
    "pate-arachide-bonmafe": "Pâte d'arachide Bonmafe — 850 g",
    "pate-arachide-pcd-500g": "Pâte d'arachide PCD — 500 g",
    "sauce-trofai-palmier-350": "Sauce graine de palme Trofai — 350 g",
    "sauce-trofai-palmier-410": "Sauce graine de palme Trofai — 410 g",
    "concentre-tomates-rolli": "Concentré de tomates Rolli — 880 g",
    "concentre-tomates-2kg": "Concentré de tomates — 2 kg",
    "jus-citron-sicile-1l": "Jus de citron — 1 L",
    # —— Fruits séchés ——
    "dattes-seches-ud": "Dattes sèches — 500 g",
    "dattes-branchees-ud": "Dattes branchées — 500 g",
    "dattes-demi-seches-ud": "Dattes demi-sèches — 500 g",
    "raisins-secs-golden": "Raisins secs golden — 500 g",
    "dakhar-sachet-150g": "Dakhar — 150 g",
    "dakhar-sachet-375g": "Dakhar — 375 g",
    # —— Conserves & aliments ——
    "corned-beef-halal": "Corned beef halal — 340 g",
    "cuisses-poulet-halal-5kg": "Cuisses de poulet halal — 5 kg",
    "cuisses-poulet-halal-10kg": "Cuisses de poulet halal — 10 kg",
    "pilons-poulet-halal-5kg": "Pilons de poulet halal — 5 kg",
    "ailes-poulet-halal-5kg": "Ailes de poulet halal — 5 kg",
    "ailes-poulet-texmex-1kg": "Ailes Tex-Mex halal — 1 kg",
    "poule-fumee-1kg": "Poule fumée — 1 kg",
    "poule-entiere-halal": "Poule entière halal — ≈ 1,1 kg",
    "ailerons-dinde-halal-1kg": "Ailerons de dinde halal — 1 kg",
    "queue-boeuf-1kg": "Queue de bœuf halal — 1 kg",
    "morceaux-boeuf-1kg": "Morceaux de bœuf halal — 1 kg",
    "morceaux-agneau-halal-1kg": "Morceaux d'agneau halal — 1 kg",
    "cotelettes-agneau-halal-1kg": "Côtelettes d'agneau halal — 1 kg",
    "gigot-agneau-halal": "Gigot d'agneau halal — ≈ 1,5 kg",
    "morceaux-mouton-halal-1kg": "Morceaux de mouton halal — 1 kg",
    "steak-hache-boeuf-halal-1kg": "Steak haché bœuf halal — 1 kg",
    "foie-boeuf-halal-1kg": "Foie de bœuf halal — 1 kg",
    "tripes-boeuf-halal-1kg": "Tripes de bœuf halal — 1 kg",
    "cotes-boeuf-halal-1kg": "Côtes de bœuf halal — 1 kg",
    "pieds-boeuf-halal-1kg": "Pieds de bœuf halal — 1 kg",
    "filets-poulet-halal-1kg": "Filets de poulet halal — 1 kg",
    "hauts-cuisse-poulet-halal-5kg": "Hauts de cuisse poulet halal — 5 kg",
    "pintade-entiere-halal": "Pintade entière halal — ≈ 1,5 kg",
    "escalopes-dinde-halal-1kg": "Escalopes de dinde halal — 1 kg",
    "merguez-boeuf-halal-1kg": "Merguez bœuf halal — 1 kg",
    "kefta-halal-1kg": "Kefta halal — 1 kg",
    "brochettes-agneau-halal-1kg": "Brochettes d'agneau halal — 1 kg",
    "brochettes-poulet-halal-1kg": "Brochettes de poulet halal — 1 kg",
    "viande-escargot-500g": "Viande d'escargot — 500–600 g",
    # —— Agneau français / Pâques ——
    "carre-box-agneau-paques-premium": "Carré Box Agneau de Pâques premium — 3,95–4,35 kg",
    "carre-box-agneau-paques": "Carré Box Agneau de Pâques — 2,75–3,05 kg",
    "gigot-agneau-francais": "Gigot d'agneau français — 2,3–2,7 kg",
    "epaule-agneau-francais": "Épaule d'agneau français — 1,3–1,6 kg",
    "carre-5-cotes-agneau-francais": "Carré 5 côtes d'agneau français — 1–1,2 kg",
    "carre-8-cotes-agneau-francais": "Carré 8 côtes d'agneau français — 1,2–1,6 kg",
    "roti-epaule-agneau-ficelle": "Rôti d'épaule d'agneau ficelle — 900 g–1,2 kg",
    "roti-noisette-agneau": "Rôti Noisette d'agneau — 1–1,5 kg",
    "agneau-cote-premiere": "Agneau côte première — 400–500 g",
    "carre-agneau-4-cotes-premieres": "Carré d'agneau 4 côtes premières — 400–500 g",
    "gigot-agneau-entier": "Gigot d'agneau entier — 2,3–2,7 kg",
    "epaule-agneau-sans-palette": "Épaule d'agneau sans palette — 1,5–1,8 kg",
    "cotes-decouvertes-agneau": "Côtes découvertes d'agneau — 400–500 g",
    "carre-8-cotes-agneau": "Carré 8 côtes d'agneau — 800 g–1,2 kg",
    "saute-gigot-agneau": "Sauté de gigot d'agneau — 800–900 g",
    "saute-epaule-agneau": "Sauté d'épaule d'agneau — 800–900 g",
    "agneau-navarin": "Agneau navarin — 900 g–1,1 kg",
    "roti-selle-agneau": "Rôti de selle d'agneau — 800 g–1 kg",
    "roti-gigotin-epaule-agneau": "Rôti Gigotin d'épaule d'agneau — 1,2–1,5 kg",
    "roti-epaule-agneau-francais": "Rôti d'épaule d'agneau français — 1,3–1,7 kg",
    "roti-selle-agneau-francais": "Rôti de selle d'agneau français — 1,2–1,6 kg",
    "navarin-agneau-francais": "Navarin d'agneau français — 900 g–1,1 kg",
    "cotes-decouvertes-agneau-francais": "Côtes découvertes d'agneau français — 450–650 g",
    # —— Bœuf / boxes ——
    "entrecote-xxl-boeuf-montbeliarde": "Entrecôte XXL de bœuf Montbéliarde — 350–450 g",
    "cote-boeuf-france-800g-1kg": "Côte de bœuf origine France — 800 g–1 kg",
    "faux-filet-boeuf-salers": "Faux-filet de bœuf Salers — 300–400 g",
    "entrecote-boeuf-charolais": "Entrecôte de bœuf Charolais — 350–450 g",
    "bavette-aloyau-x10": "Bavette d'aloyau x10 — 1,6–1,7 kg",
    "pave-rumsteck-boeuf-salers-x2": "Pavé de rumsteck de bœuf Salers x2 — 300–400 g",
    "entrecote-boeuf-selection-boucher-x2": "Entrecôte de bœuf Sélection du Boucher x2 — 400–600 g",
    "entrecote-boeuf-xxl-selection-boucher": "Entrecôte de bœuf XXL Sélection du Boucher — 350–450 g",
    "paleron-boeuf-bourguignon": "Paleron de bœuf pour bourguignon — 800–900 g",
    "tomahawk-boeuf-blonde-galice": "Tomahawk de bœuf Blonde de Galice — 1–1,5 kg",
    "huile-speciale-fondue-1l": "Huile spéciale fondue — 1 L",
    "cote-boeuf-france-1-15kg": "Côte de bœuf origine France — 1–1,5 kg",
    "cote-boeuf-selection-boucher-115-14": "Côte de bœuf Sélection du Boucher — 1,15–1,4 kg",
    "cote-boeuf-selection-boucher-950-115": "Côte de bœuf Sélection du Boucher — 950 g–1,15 kg",
    "tournedos-rumsteck-boeuf-salers-x2": "Tournedos de rumsteck de bœuf Salers x2 — 300–400 g",
    "tournedos-filet-boeuf-salers-x2": "Tournedos de filet de bœuf Salers x2 — 300–400 g",
    "gite-boeuf-pot-au-feu": "Gîte de bœuf pour pot-au-feu — 1,5–1,6 kg",
    "viande-fondue-boeuf-salers": "Viande à fondue de bœuf Salers — 350–450 g",
    "roti-boeuf-salers-800g-1kg": "Rôti de bœuf Salers — 800 g–1 kg",
    "roti-boeuf-salers-115-135": "Rôti de bœuf Salers — 1,15–1,35 kg",
    "roti-filet-boeuf-francais-115-135": "Rôti de filet de bœuf français — 1,15–1,35 kg",
    "roti-filet-boeuf-francais-800-900": "Rôti de filet de bœuf français — 800–900 g",
    "roti-boeuf-tende-tranche-2-22": "Rôti de bœuf tende de tranche — 2–2,2 kg",
    "roti-boeuf-tende-tranche-115-135": "Rôti de bœuf tende de tranche — 1,15–1,35 kg",
    "roti-boeuf-tende-tranche-800g-1kg": "Rôti de bœuf tende de tranche — 800 g–1 kg",
    "steak-tartare-boeuf-francais-180g": "Steak tartare de bœuf français 5% MG — 180 g",
    "onglet-boeuf-x2": "Onglet de bœuf x2 — 300–400 g",
    "steak-poire-boeuf-x2": "Steak de poire de bœuf x2 — 300–400 g",
    "bavette-aloyau-x2": "Bavette d'aloyau x2 — 300–400 g",
    "emince-boeuf-500g": "Émincé de bœuf — ±500 g",
    "carre-box-boeuf-100": "Carré Box 100% bœuf — 3,85–4,85 kg",
    "carre-box-regime-proteine-rotis": "Carré Box régime protéiné avec rôtis — 4–5,1 kg",
    "carre-box-viande-famille-nombreuse": "Carré Box viande famille nombreuse — 6,2–6,9 kg",
    "carre-box-degustation-plaisir": "Carré Box dégustation plaisir — 3–4 kg",
    "carre-box-viande-familial-authentique": "Carré Box viande familial authentique — 4,8–7 kg",
    "carre-box-regime-proteine": "Carré Box régime protéiné — 3,7–5 kg",
    "entrecote-boeuf-francaise-xxl": "Entrecôte de bœuf française XXL — 350–450 g",
    "entrecote-boeuf-francaise": "Entrecôte de bœuf française — 250–350 g",
    "filet-boeuf-entier": "Filet de bœuf entier — 1,5–2,5 kg",
    "filet-boeuf-francais-entier": "Filet de bœuf français entier — 1,6–2 kg",
    "cote-boeuf-angus": "Côte de bœuf Angus — 950 g–1,15 kg",
    "picanha-boeuf-angus": "Picanha de bœuf Angus — 1,5–2,5 kg",
    "filet-boeuf-angus-entier": "Filet de bœuf Angus entier — 1,5–2,5 kg",
    "entrecote-boeuf-wagyu-japonais": "Entrecôte de bœuf Wagyu japonais — 200–250 g",
    "onglet-boeuf-angus-x2": "Onglet de bœuf Angus x2 — 300–400 g",
    "entrecote-xxl-boeuf-salers": "Entrecôte XXL de bœuf Salers — 350–450 g",
    "entrecote-boeuf-salers": "Entrecôte de bœuf Salers — 250–350 g",
    "maad-230g": "Maad en boîte — 230 g",
    "maad-400g": "Maad en boîte — 400 g",
    "poisson-fume-ud": "Poisson fumé — 500 g",
    "rouge-barbet-ud": "Poisson rouge barbet — 1 kg",
    "pate-sardinelle-pinton": "Pâte de sardinelle Pinton",
    "sardinelle-pilchards-tomate": "Sardinelles à la tomate",
}


def _normalize_weight(weight_info: str | None) -> str | None:
    if not weight_info:
        return None
    part = weight_info.split("—")[0].split(",")[0].strip()
    return part or None


def display_name_for_product(slug: str, weight_info: str | None = None, fallback: str = "") -> str:
    """Retourne le nom boutique cohérent pour un slug."""
    if slug in PRODUCT_DISPLAY_NAMES:
        return PRODUCT_DISPLAY_NAMES[slug]
    base = fallback.strip() or slug.replace("-", " ").title()
    w = _normalize_weight(weight_info)
    if w and w.lower() not in base.lower():
        return f"{base} — {w}"
    return base


def apply_display_name(row: dict) -> dict:
    """Enrichit une ligne catalogue avec le nom d'affichage."""
    slug = row.get("slug", "")
    row = dict(row)
    row["name"] = display_name_for_product(slug, row.get("weight_info"), row.get("name", ""))
    return row
